# Generated by Django 5.2.5 on 2025-09-30 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesseract_config', models.TextField(default='--oem 3 --psm 6', verbose_name='Configuración Tesseract')),
                ('confianza_minima', models.FloatField(default=60.0, verbose_name='Confianza Mínima OCR (%)')),
                ('tolerancia_posicion_x', models.FloatField(default=5.0, verbose_name='Tolerancia Posición X (puntos)')),
                ('tolerancia_posicion_y', models.FloatField(default=5.0, verbose_name='Tolerancia Posición Y (puntos)')),
                ('permitir_texto_parcial', models.BooleanField(default=False, verbose_name='Permitir Texto Parcial')),
                ('detectar_firmas', models.BooleanField(default=True, verbose_name='Detectar Presencia de Firmas')),
                ('procesar_imagenes', models.BooleanField(default=True, verbose_name='Procesar Imágenes Adjuntas')),
                ('guardar_imagenes_temporales', models.BooleanField(default=False, verbose_name='Guardar Imágenes Temporales')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Configuración OCR',
                'verbose_name_plural': 'Configuraciones OCR',
                'db_table': 'ocr_configuration',
            },
        ),
        migrations.CreateModel(
            name='FieldValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(max_length=100, verbose_name='Nombre del Campo')),
                ('descripcion_campo', models.CharField(max_length=255, verbose_name='Descripción del Campo')),
                ('tipo_campo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('firma', 'Firma'), ('celda_x', 'Celda con X'), ('total', 'Campo de Total')], max_length=20, verbose_name='Tipo de Campo')),
                ('pagina_tipica', models.IntegerField(default=1, verbose_name='Página Típica')),
                ('posicion_x_relativa', models.FloatField(default=0.0, verbose_name='Posición X Relativa')),
                ('posicion_y_relativa', models.FloatField(default=0.0, verbose_name='Posición Y Relativa')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Campo Obligatorio')),
                ('patron_validacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patrón de Validación (Regex)')),
                ('valor_minimo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Mínimo')),
                ('valor_maximo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Máximo')),
                ('detectar_posicion_x', models.BooleanField(default=False, verbose_name='Detectar Posición Exacta de X')),
                ('tolerancia_posicion', models.FloatField(default=3.0, verbose_name='Tolerancia de Posición (puntos)')),
                ('activo', models.BooleanField(default=True, verbose_name='Regla Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Regla de Validación de Campo',
                'verbose_name_plural': 'Reglas de Validación de Campos',
                'db_table': 'ocr_field_validation_rules',
                'ordering': ['nombre_campo'],
                'indexes': [models.Index(fields=['tipo_campo'], name='ocr_field_v_tipo_ca_fd6225_idx'), models.Index(fields=['activo'], name='ocr_field_v_activo_c5e438_idx')],
            },
        ),
        migrations.CreateModel(
            name='PDFValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('archivo_path', models.CharField(max_length=500, verbose_name='Ruta del Archivo')),
                ('sede_educativa', models.CharField(max_length=200, verbose_name='Sede Educativa')),
                ('mes_atencion', models.CharField(max_length=20, verbose_name='Mes de Atención')),
                ('ano', models.IntegerField(verbose_name='Año')),
                ('tipo_complemento', models.CharField(max_length=20, verbose_name='Tipo de Complemento')),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=20, verbose_name='Estado')),
                ('total_errores', models.IntegerField(default=0, verbose_name='Total de Errores')),
                ('errores_criticos', models.IntegerField(default=0, verbose_name='Errores Críticos')),
                ('errores_advertencia', models.IntegerField(default=0, verbose_name='Advertencias')),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Procesamiento')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('tiempo_procesamiento', models.FloatField(blank=True, null=True, verbose_name='Tiempo de Procesamiento (segundos)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Validación PDF OCR',
                'verbose_name_plural': 'Validaciones PDF OCR',
                'db_table': 'ocr_pdf_validation',
                'ordering': ['-fecha_procesamiento'],
                'indexes': [models.Index(fields=['sede_educativa', 'mes_atencion', 'ano'], name='ocr_pdf_val_sede_ed_132b06_idx'), models.Index(fields=['estado'], name='ocr_pdf_val_estado_789c65_idx'), models.Index(fields=['fecha_procesamiento'], name='ocr_pdf_val_fecha_p_14fe39_idx')],
            },
        ),
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_error', models.CharField(max_length=50, verbose_name='Tipo de Error')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('pagina', models.IntegerField(verbose_name='Página')),
                ('fila_estudiante', models.IntegerField(blank=True, null=True, verbose_name='Fila del Estudiante')),
                ('columna_campo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo/Columna')),
                ('valor_esperado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Esperado')),
                ('valor_encontrado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Encontrado')),
                ('coordenada_x', models.FloatField(blank=True, null=True, verbose_name='Coordenada X')),
                ('coordenada_y', models.FloatField(blank=True, null=True, verbose_name='Coordenada Y')),
                ('severidad', models.CharField(choices=[('critico', 'Crítico'), ('advertencia', 'Advertencia'), ('info', 'Información')], default='advertencia', max_length=20, verbose_name='Severidad')),
                ('resuelto', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('validacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='ocr_validation.pdfvalidation', verbose_name='Validación')),
            ],
            options={
                'verbose_name': 'Error de Validación',
                'verbose_name_plural': 'Errores de Validación',
                'db_table': 'ocr_validation_errors',
                'ordering': ['pagina', 'fila_estudiante', 'tipo_error'],
                'indexes': [models.Index(fields=['validacion', 'tipo_error'], name='ocr_validat_validac_9471c8_idx'), models.Index(fields=['severidad'], name='ocr_validat_severid_f87f8b_idx'), models.Index(fields=['resuelto'], name='ocr_validat_resuelt_95dc6e_idx')],
            },
        ),
    ]
