# Generated by Django 4.2.7 on 2025-10-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_validation', '0003_add_metodo_ocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfvalidation',
            name='datos_estructurados',
            field=models.JSONField(blank=True, help_text='Datos tabulares extraídos del PDF en formato JSON', null=True, verbose_name='Datos Estructurados JSON'),
        ),
        migrations.AddField(
            model_name='pdfvalidation',
            name='metadatos_extraccion',
            field=models.JSONField(blank=True, help_text='Información sobre el proceso de extracción', null=True, verbose_name='Metadatos de Extracción'),
        ),
        migrations.AddField(
            model_name='pdfvalidation',
            name='texto_completo',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Completo Extraído'),
        ),
        migrations.AlterField(
            model_name='pdfvalidation',
            name='metodo_ocr',
            field=models.CharField(choices=[('landingai', 'LandingAI ADE')], default='landingai', max_length=20, verbose_name='Método OCR'),
        ),
    ]
