[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && cd erp_chvs && python manage.py collectstatic --noinput"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/"
timeout = 100
interval = 60
