# Generated by Django 5.2.5 on 2026-03-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verificacionchecklist',
            name='unique_registro_item',
        ),
        migrations.RenameIndex(
            model_name='historialestado',
            new_name='contabilida_registr_8ac0ca_idx',
            old_name='contabilida_registr_h_idx',
        ),
        migrations.RenameIndex(
            model_name='registrocontable',
            new_name='contabilida_lider_i_ccb277_idx',
            old_name='contabilida_lider_i_idx',
        ),
        migrations.RenameIndex(
            model_name='registrocontable',
            new_name='contabilida_estado_1bab9f_idx',
            old_name='contabilida_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='registrocontable',
            new_name='contabilida_tipo_8f865c_idx',
            old_name='contabilida_tipo_p_idx',
        ),
        migrations.AlterUniqueTogether(
            name='verificacionchecklist',
            unique_together={('registro', 'item')},
        ),
    ]
