# Generated by Django 5.2.5 on 2026-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_checklist_materias_primas'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_contable',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado Contable'),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_orden_compra',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Orden de Compra'),
        ),
        migrations.AddField(
            model_name='factura',
            name='referencia_appd',
            field=models.CharField(blank=True, max_length=50, verbose_name='Referencia APPD'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('ENVIO', 'Envío'), ('CONFIRMACION_RECEPCION', 'Confirmación de Recepción'), ('DEVOLUCION_COMPRAS', 'Devolución por Compras'), ('REENVIO', 'Reenvío'), ('CONFIRMACION_REENTREGA', 'Confirmación de Reentrega'), ('APROBACION_COMPRAS', 'Aprobación por Compras'), ('INICIO_REVISION_CONTABILIDAD', 'Inicio Revisión Contabilidad'), ('OBSERVACION_CONTABILIDAD', 'Observación de Contabilidad'), ('RESPUESTA_COMPRAS', 'Respuesta de Compras a Observación'), ('APROBACION_CONTABILIDAD', 'Aprobación por Contabilidad'), ('CIERRE', 'Cierre'), ('DEVOLUCION_CONTABILIDAD', 'Devolución por Contabilidad')], max_length=40, verbose_name='Acción'),
        ),
    ]
