# Generated by Django 5.2.5 on 2026-04-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_factura_campos_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('CREDITO', 'Crédito'), ('CONTADO', 'Contado')], max_length=10, verbose_name='Método de Pago'),
        ),
    ]
