# Generated by Django 5.2.5 on 2026-04-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_factura_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Contrato'),
        ),
    ]
