# Generated by Django 5.2.5 on 2026-02-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadesDeConsumo',
            fields=[
                ('id_modalidades', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Modalidad')),
                ('modalidad', models.CharField(max_length=150, verbose_name='Modalidad')),
                ('cod_modalidad', models.CharField(max_length=20, verbose_name='Código de Modalidad')),
            ],
            options={
                'verbose_name': 'Modalidad de Consumo',
                'verbose_name_plural': 'Modalidades de Consumo',
                'db_table': 'modalidades_de_consumo',
            },
        ),
        migrations.CreateModel(
            name='PrincipalDepartamento',
            fields=[
                ('codigo_departamento', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'db_table': 'principal_departamento',
            },
        ),
        migrations.CreateModel(
            name='PrincipalMunicipio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_municipio', models.IntegerField()),
                ('nombre_municipio', models.CharField(max_length=100)),
                ('codigo_departamento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'principal_municipio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TablaGradosEscolaresUapa',
            fields=[
                ('id_grado_escolar_uapa', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código Grado Escolar UAPA')),
                ('nivel_escolar_uapa', models.CharField(max_length=100, verbose_name='Nivel Escolar UAPA')),
            ],
            options={
                'verbose_name': 'Grado Escolar UAPA',
                'verbose_name_plural': 'Grados Escolares UAPA',
                'db_table': 'tabla_grados_escolares_uapa',
                'ordering': ['id_grado_escolar_uapa'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_documento', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Documento')),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('codigo_documento', models.IntegerField(verbose_name='Código Documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='TipoGenero',
            fields=[
                ('id_genero', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Género')),
                ('genero', models.CharField(max_length=50, verbose_name='Género')),
                ('codigo_genero', models.IntegerField(verbose_name='Código Género')),
            ],
            options={
                'verbose_name': 'Tipo de Género',
                'verbose_name_plural': 'Tipos de Género',
                'db_table': 'tipo_genero',
            },
        ),
        migrations.CreateModel(
            name='NivelGradoEscolar',
            fields=[
                ('id_grado_escolar', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Grado Escolar')),
                ('grados_sedes', models.CharField(max_length=200, verbose_name='Grados Sedes')),
                ('nivel_escolar_uapa', models.ForeignKey(db_column='nivel_escolar_uapa', on_delete=django.db.models.deletion.PROTECT, related_name='niveles_grado', to='principal.tablagradosescolaresuapa', verbose_name='Nivel Escolar UAPA')),
            ],
            options={
                'verbose_name': 'Nivel Grado Escolar',
                'verbose_name_plural': 'Niveles Grado Escolar',
                'db_table': 'nivel_grado_escolar',
                'ordering': ['id_grado_escolar'],
            },
        ),
        migrations.CreateModel(
            name='MunicipioModalidades',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios_asignados', to='principal.modalidadesdeconsumo', verbose_name='Modalidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades_configuradas', to='principal.principalmunicipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Modalidad por Municipio',
                'verbose_name_plural': 'Modalidades por Municipio',
                'db_table': 'municipio_modalidades',
                'ordering': ['municipio__nombre_municipio', 'modalidad__modalidad'],
                'unique_together': {('municipio', 'modalidad')},
            },
        ),
    ]
