# Generated by Django 5.2.5 on 2026-02-15 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(choices=[('CALI', 'Cali'), ('YUMBO', 'Yumbo'), ('AMBAS', 'Ambas')], default='AMBAS', max_length=10, verbose_name='Sede Asignada')),
                ('modulo_defecto', models.CharField(choices=[('NUTRICION', 'Nutrición'), ('FACTURACION', 'Facturación'), ('PLANEACION', 'Planeación'), ('ADMINISTRACION', 'Administración')], default='ADMINISTRACION', max_length=20, verbose_name='Módulo Principal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'perfil_usuario',
            },
        ),
    ]
