# Generated by Django 5.2.5 on 2025-09-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(db_column='codigo_departamento', on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='principal.departamento'),
        ),
    ]
