# Generated by Django 5.2.5 on 2025-09-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_municipio_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalMunicipio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_municipio', models.IntegerField()),
                ('nombre_municipio', models.CharField(max_length=100)),
                ('codigo_departamento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'principal_municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalDepartamento',
            fields=[
                ('codigo_departamento', models.CharField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'db_table': 'principal_departamento',
            },
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='departamento',
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
