# Generated by Django 5.2.5 on 2025-09-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_principalmunicipio_principaldepartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principaldepartamento',
            name='codigo_departamento',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
