# Generated by Django 5.2.5 on 2025-09-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_principaldepartamento_codigo_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principalmunicipio',
            options={'managed': True},
        ),
    ]
