# Generated by Django 5.2.5 on 2026-02-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_delete_municipiomodalidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='modulo_defecto',
            field=models.CharField(choices=[('NUTRICION', 'Nutrición'), ('FACTURACION', 'Facturación'), ('PLANEACION', 'Planeación'), ('COSTOS', 'Costos'), ('ADMINISTRACION', 'Administración')], default='ADMINISTRACION', max_length=20, verbose_name='Módulo Principal'),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='modulo',
            field=models.CharField(choices=[('facturacion', 'Facturación'), ('nutricion', 'Nutrición'), ('planeacion', 'Planeación'), ('costos', 'Costos'), ('principal', 'Datos Maestros'), ('dashboard', 'Dashboard')], max_length=50, verbose_name='Módulo'),
        ),
    ]
