# Generated by Django 5.2.5 on 2026-03-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_perfilusuario_modulo_defecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='modulo',
            field=models.CharField(choices=[('facturacion', 'Facturación'), ('nutricion', 'Nutrición'), ('planeacion', 'Planeación'), ('costos', 'Costos'), ('logistica', 'Logística'), ('principal', 'Datos Maestros'), ('dashboard', 'Dashboard')], max_length=50, verbose_name='Módulo'),
        ),
    ]
