# Generated by Django 5.2.5 on 2025-09-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_fix_municipio_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadesDeConsumo',
            fields=[
                ('id_modalidades', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Modalidad')),
                ('modalidad', models.CharField(max_length=150, verbose_name='Modalidad')),
                ('cod_modalidad', models.CharField(max_length=20, verbose_name='Código de Modalidad')),
            ],
            options={
                'verbose_name': 'Modalidad de Consumo',
                'verbose_name_plural': 'Modalidades de Consumo',
                'db_table': 'modalidades_de_consumo',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_documento', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Documento')),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('codigo_documento', models.IntegerField(verbose_name='Código Documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='TipoGenero',
            fields=[
                ('id_genero', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Género')),
                ('genero', models.CharField(max_length=50, verbose_name='Género')),
                ('codigo_genero', models.IntegerField(verbose_name='Código Género')),
            ],
            options={
                'verbose_name': 'Tipo de Género',
                'verbose_name_plural': 'Tipos de Género',
                'db_table': 'tipo_genero',
            },
        ),
    ]
