# Generated by Django 5.2.5 on 2026-03-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_registroactividad_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='modulo',
            field=models.CharField(choices=[('facturacion', 'Facturación'), ('nutricion', 'Nutrición'), ('planeacion', 'Planeación'), ('costos', 'Costos'), ('logistica', 'Logística'), ('principal', 'Datos Maestros'), ('agente', 'Agente IA'), ('dashboard', 'Dashboard')], max_length=50, verbose_name='Módulo'),
        ),
    ]
