# Generated by Django 5.2.5 on 2025-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_modalidadesdeconsumo_tipodocumento_tipogenero'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelGradoEscolar',
            fields=[
                ('id_grado_escolar', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Grado Escolar')),
                ('grados_sedes', models.CharField(max_length=200, verbose_name='Grados Sedes')),
                ('nivel_escolar_uapa', models.CharField(max_length=100, verbose_name='Nivel Escolar UAPA')),
            ],
            options={
                'verbose_name': 'Nivel Grado Escolar',
                'verbose_name_plural': 'Niveles Grado Escolar',
                'db_table': 'nivel_grado_escolar',
                'ordering': ['id_grado_escolar'],
            },
        ),
    ]
