# Generated by Django 5.2.5 on 2025-10-04 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_nivelgradoescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipioModalidades',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios_asignados', to='principal.modalidadesdeconsumo', verbose_name='Modalidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades_configuradas', to='principal.principalmunicipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Modalidad por Municipio',
                'verbose_name_plural': 'Modalidades por Municipio',
                'db_table': 'municipio_modalidades',
                'ordering': ['municipio__nombre_municipio', 'modalidad__modalidad'],
                'unique_together': {('municipio', 'modalidad')},
            },
        ),
    ]
