# Generated by Django 5.2.5 on 2026-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_agregar_modulo_contabilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrograma',
            fields=[
                ('id_tipo_programa', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tiene_niveles', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Programa',
                'verbose_name_plural': 'Tipos de Programa',
                'db_table': 'principal_tipo_programa',
            },
        ),
    ]
