# Generated by Django 5.2.5 on 2025-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_municipiomodalidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaGradosEscolaresUapa',
            fields=[
                ('id_grado_escolar_uapa', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código Grado Escolar UAPA')),
                ('nivel_escolar_uapa', models.CharField(max_length=100, verbose_name='Nivel Escolar UAPA')),
            ],
            options={
                'verbose_name': 'Grado Escolar UAPA',
                'verbose_name_plural': 'Grados Escolares UAPA',
                'db_table': 'tabla_grados_escolares_uapa',
                'ordering': ['id_grado_escolar_uapa'],
            },
        ),
    ]
