# Generated by Django 5.2.5 on 2025-10-04 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_tablagradosescolaresuapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelgradoescolar',
            name='nivel_escolar_uapa',
            field=models.ForeignKey(db_column='nivel_escolar_uapa', on_delete=django.db.models.deletion.PROTECT, related_name='niveles_grado', to='principal.tablagradosescolaresuapa', verbose_name='Nivel Escolar UAPA'),
        ),
    ]
