# Generated by Django 5.2.5 on 2026-02-09 20:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planeacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListadosFocalizacion',
            fields=[
                ('id_listados', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID Listados')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)], verbose_name='Año')),
                ('etc', models.CharField(max_length=100, verbose_name='ETC (Entidad Territorial)')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución Educativa')),
                ('sede', models.CharField(max_length=200, verbose_name='Sede Educativa')),
                ('tipodoc', models.CharField(max_length=10, verbose_name='Tipo de Documento')),
                ('doc', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('apellido1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Apellido')),
                ('nombre1', models.CharField(max_length=100, verbose_name='Primer Nombre')),
                ('nombre2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Nombre')),
                ('fecha_nacimiento', models.CharField(max_length=20, verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Edad')),
                ('etnia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Etnia')),
                ('genero', models.CharField(max_length=10, verbose_name='Género')),
                ('grado_grupos', models.CharField(max_length=20, verbose_name='Grado y Grupos')),
                ('complemento_alimentario_preparado_am', models.CharField(blank=True, max_length=10, null=True, verbose_name='Complemento Alimentario AM')),
                ('complemento_alimentario_preparado_pm', models.CharField(blank=True, max_length=10, null=True, verbose_name='Complemento Alimentario PM')),
                ('almuerzo_jornada_unica', models.CharField(blank=True, max_length=10, null=True, verbose_name='Almuerzo Jornada Única')),
                ('refuerzo_complemento_am_pm', models.CharField(blank=True, max_length=10, null=True, verbose_name='Refuerzo Complemento AM/PM')),
                ('focalizacion', models.CharField(max_length=10, verbose_name='Focalización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeacion.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Listado de Focalización',
                'verbose_name_plural': 'Listados de Focalización',
                'db_table': 'listados_focalizacion',
                'ordering': ['-ano', 'etc', 'institucion', 'sede'],
                'indexes': [models.Index(fields=['ano', 'etc'], name='listados_fo_ano_e04e90_idx'), models.Index(fields=['focalizacion'], name='listados_fo_focaliz_52f98e_idx'), models.Index(fields=['sede'], name='listados_fo_sede_1c7c6d_idx'), models.Index(fields=['doc'], name='listados_fo_doc_2f8909_idx'), models.Index(fields=['fecha_creacion'], name='listados_fo_fecha_c_ef0e38_idx')],
            },
        ),
    ]
