# Generated by Django 5.2.5 on 2026-02-16 00:13
# Modified manually to fix db_table case and add db_column to ForeignKey

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('planeacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listadosfocalizacion',
            new_name='facturacion_ano_527684_idx',
            old_name='listados_fo_ano_e04e90_idx',
        ),
        migrations.RenameIndex(
            model_name='listadosfocalizacion',
            new_name='facturacion_focaliz_843986_idx',
            old_name='listados_fo_focaliz_52f98e_idx',
        ),
        migrations.RenameIndex(
            model_name='listadosfocalizacion',
            new_name='facturacion_sede_2b0254_idx',
            old_name='listados_fo_sede_1c7c6d_idx',
        ),
        migrations.RenameIndex(
            model_name='listadosfocalizacion',
            new_name='facturacion_doc_6b4421_idx',
            old_name='listados_fo_doc_2f8909_idx',
        ),
        migrations.RenameIndex(
            model_name='listadosfocalizacion',
            new_name='facturacion_fecha_c_761583_idx',
            old_name='listados_fo_fecha_c_ef0e38_idx',
        ),
        # Corregir nombre de tabla a minúsculas (PostgreSQL case-sensitive)
        migrations.AlterModelTable(
            name='listadosfocalizacion',
            table='facturacion_listados_focalizacion',
        ),
        # Agregar db_column explícito al ForeignKey programa
        migrations.AlterField(
            model_name='listadosfocalizacion',
            name='programa',
            field=models.ForeignKey(
                blank=True,
                db_column='programa_id',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='planeacion.programa',
                verbose_name='Programa'
            ),
        ),
    ]
