# Generated by Django 5.2.5 on 2025-09-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listadosfocalizacion',
            new_name='listados_fo_ano_e04e90_idx',
            old_name='facturacion_listado_ano_etc_idx',
        ),
        migrations.RenameIndex(
            model_name='listadosfocalizacion',
            new_name='listados_fo_focaliz_52f98e_idx',
            old_name='facturacion_listado_focalizacion_idx',
        ),
        migrations.RenameIndex(
            model_name='listadosfocalizacion',
            new_name='listados_fo_sede_1c7c6d_idx',
            old_name='facturacion_listado_sede_idx',
        ),
        migrations.RenameIndex(
            model_name='listadosfocalizacion',
            new_name='listados_fo_doc_2f8909_idx',
            old_name='facturacion_listado_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='listadosfocalizacion',
            new_name='listados_fo_fecha_c_ef0e38_idx',
            old_name='facturacion_listado_fecha_creacion_idx',
        ),
    ]
