# Generated by Django 5.2.5 on 2026-02-16 02:09
# Modified to be idempotent with proper state management

from django.db import migrations


def index_exists(schema_editor, index_name):
    """Verifica si un índice existe en la base de datos."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE schemaname = 'public'
                AND indexname = %s
            );
        """, [index_name])
        return cursor.fetchone()[0]


def table_exists(schema_editor, table_name):
    """Verifica si una tabla existe en la base de datos."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = %s
            );
        """, [table_name])
        return cursor.fetchone()[0]


def rename_indexes_and_table(apps, schema_editor):
    """
    Renombra índices y tabla solo si los nombres antiguos existen.
    Si los nombres nuevos ya existen, no hace nada.
    """
    # Renombrar índices
    index_renames = [
        ('facturacion_ano_527684_idx', 'listados_fo_ano_e04e90_idx'),
        ('facturacion_focaliz_843986_idx', 'listados_fo_focaliz_52f98e_idx'),
        ('facturacion_sede_2b0254_idx', 'listados_fo_sede_1c7c6d_idx'),
        ('facturacion_doc_6b4421_idx', 'listados_fo_doc_2f8909_idx'),
        ('facturacion_fecha_c_761583_idx', 'listados_fo_fecha_c_ef0e38_idx'),
    ]

    for old_name, new_name in index_renames:
        if index_exists(schema_editor, old_name):
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name}')
        elif not index_exists(schema_editor, new_name):
            print(f"⚠️  Warning: Neither {old_name} nor {new_name} exists")

    # Renombrar tabla
    old_table = 'facturacion_Listados_Focalizacion'
    new_table = 'facturacion_listados_focalizacion'

    if table_exists(schema_editor, old_table):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f'ALTER TABLE "{old_table}" RENAME TO "{new_table}"')
    elif not table_exists(schema_editor, new_table):
        print(f"⚠️  Warning: Neither {old_table} nor {new_table} exists")


def reverse_rename(apps, schema_editor):
    """Revertir cambios (para rollback)."""
    # Revertir índices
    index_renames = [
        ('listados_fo_ano_e04e90_idx', 'facturacion_ano_527684_idx'),
        ('listados_fo_focaliz_52f98e_idx', 'facturacion_focaliz_843986_idx'),
        ('listados_fo_sede_1c7c6d_idx', 'facturacion_sede_2b0254_idx'),
        ('listados_fo_doc_2f8909_idx', 'facturacion_doc_6b4421_idx'),
        ('listados_fo_fecha_c_ef0e38_idx', 'facturacion_fecha_c_761583_idx'),
    ]

    for old_name, new_name in index_renames:
        if index_exists(schema_editor, old_name):
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name}')

    # Revertir tabla
    old_table = 'facturacion_listados_focalizacion'
    new_table = 'facturacion_Listados_Focalizacion'

    if table_exists(schema_editor, old_table):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f'ALTER TABLE "{old_table}" RENAME TO "{new_table}"')


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_fix_db_table_and_programa_column'),
    ]

    operations = [
        # Usar SeparateDatabaseAndState para ejecutar Python pero actualizar estado de Django
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Operaciones idempotentes en la BD
                migrations.RunPython(
                    rename_indexes_and_table,
                    reverse_rename,
                ),
            ],
            state_operations=[
                # Operaciones que actualizan el estado de Django
                migrations.RenameIndex(
                    model_name='listadosfocalizacion',
                    new_name='listados_fo_ano_e04e90_idx',
                    old_name='facturacion_ano_527684_idx',
                ),
                migrations.RenameIndex(
                    model_name='listadosfocalizacion',
                    new_name='listados_fo_focaliz_52f98e_idx',
                    old_name='facturacion_focaliz_843986_idx',
                ),
                migrations.RenameIndex(
                    model_name='listadosfocalizacion',
                    new_name='listados_fo_sede_1c7c6d_idx',
                    old_name='facturacion_sede_2b0254_idx',
                ),
                migrations.RenameIndex(
                    model_name='listadosfocalizacion',
                    new_name='listados_fo_doc_2f8909_idx',
                    old_name='facturacion_doc_6b4421_idx',
                ),
                migrations.RenameIndex(
                    model_name='listadosfocalizacion',
                    new_name='listados_fo_fecha_c_ef0e38_idx',
                    old_name='facturacion_fecha_c_761583_idx',
                ),
                migrations.AlterModelTable(
                    name='listadosfocalizacion',
                    table='facturacion_listados_focalizacion',
                ),
            ],
        ),
    ]
