# Generated by Django 5.2.5 on 2025-09-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_remove_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadosfocalizacion',
            name='doc',
            field=models.CharField(max_length=50, verbose_name='Número de Documento'),
        ),
    ]
