# Generated by Django 5.2.5 on 2026-02-16 02:09
# Modified to be idempotent: only renames indexes if they exist

from django.db import migrations


def index_exists(schema_editor, index_name):
    """Verifica si un índice existe en la base de datos."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE schemaname = 'public'
                AND indexname = %s
            );
        """, [index_name])
        return cursor.fetchone()[0]


def table_exists(schema_editor, table_name):
    """Verifica si una tabla existe en la base de datos."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = %s
            );
        """, [table_name])
        return cursor.fetchone()[0]


def rename_indexes_forward(apps, schema_editor):
    """
    Renombra índices solo si los nombres antiguos existen.
    Si los nombres nuevos ya existen, no hace nada.
    """
    renames = [
        ('facturacion_ano_527684_idx', 'listados_fo_ano_e04e90_idx'),
        ('facturacion_focaliz_843986_idx', 'listados_fo_focaliz_52f98e_idx'),
        ('facturacion_sede_2b0254_idx', 'listados_fo_sede_1c7c6d_idx'),
        ('facturacion_doc_6b4421_idx', 'listados_fo_doc_2f8909_idx'),
        ('facturacion_fecha_c_761583_idx', 'listados_fo_fecha_c_ef0e38_idx'),
    ]

    for old_name, new_name in renames:
        if index_exists(schema_editor, old_name):
            # El índice antiguo existe, renombrarlo
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name}')
        elif index_exists(schema_editor, new_name):
            # El índice nuevo ya existe, no hacer nada
            pass
        else:
            # Ninguno existe - advertir pero continuar
            print(f"⚠️  Warning: Neither {old_name} nor {new_name} exists")


def rename_indexes_backward(apps, schema_editor):
    """Revertir el renombrado de índices (para rollback)."""
    renames = [
        ('listados_fo_ano_e04e90_idx', 'facturacion_ano_527684_idx'),
        ('listados_fo_focaliz_52f98e_idx', 'facturacion_focaliz_843986_idx'),
        ('listados_fo_sede_1c7c6d_idx', 'facturacion_sede_2b0254_idx'),
        ('listados_fo_doc_2f8909_idx', 'facturacion_doc_6b4421_idx'),
        ('listados_fo_fecha_c_ef0e38_idx', 'facturacion_fecha_c_761583_idx'),
    ]

    for old_name, new_name in renames:
        if index_exists(schema_editor, old_name):
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name}')


def rename_table_forward(apps, schema_editor):
    """
    Renombra la tabla solo si tiene el nombre antiguo.
    Si ya tiene el nombre correcto, no hace nada.
    """
    old_table = 'facturacion_Listados_Focalizacion'
    new_table = 'facturacion_listados_focalizacion'

    if table_exists(schema_editor, old_table):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f'ALTER TABLE "{old_table}" RENAME TO "{new_table}"')
    elif table_exists(schema_editor, new_table):
        # La tabla ya tiene el nombre correcto
        pass
    else:
        print(f"⚠️  Warning: Neither {old_table} nor {new_table} exists")


def rename_table_backward(apps, schema_editor):
    """Revertir el renombrado de tabla."""
    old_table = 'facturacion_Listados_Focalizacion'
    new_table = 'facturacion_listados_focalizacion'

    if table_exists(schema_editor, new_table):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f'ALTER TABLE "{new_table}" RENAME TO "{old_table}"')


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_fix_db_table_and_programa_column'),
    ]

    operations = [
        # Renombrar índices de manera idempotente
        migrations.RunPython(
            rename_indexes_forward,
            rename_indexes_backward,
        ),
        # Renombrar tabla de manera idempotente
        migrations.RunPython(
            rename_table_forward,
            rename_table_backward,
        ),
    ]
