# Generated by Django 4.2.7 on 2025-11-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0013_planificacionraciones_nombre_programa'),
        ('facturacion', '0004_alter_listadosfocalizacion_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadosfocalizacion',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeacion.programa', verbose_name='Programa'),
        ),
    ]
