# Generated by Django 5.2.5 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_rename_facturacion_ano_527684_idx_listados_fo_ano_e04e90_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listadosfocalizacion',
            index=models.Index(fields=['programa', 'focalizacion'], name='listados_prog_focal_idx'),
        ),
        migrations.AddIndex(
            model_name='listadosfocalizacion',
            index=models.Index(fields=['programa', 'focalizacion', 'sede'], name='listados_prog_focal_sede_idx'),
        ),
        migrations.AddIndex(
            model_name='listadosfocalizacion',
            index=models.Index(fields=['programa', 'sede'], name='listados_prog_sede_idx'),
        ),
    ]
