# Generated by Django 5.2.5 on 2026-04-14 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_add_composite_indexes'),
        ('planeacion', '0005_add_tipo_programa_to_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RectorInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rector', models.CharField(max_length=255, verbose_name='Nombre del Rector')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('institucion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rector', to='planeacion.institucioneseducativas', verbose_name='Institución Educativa')),
            ],
            options={
                'verbose_name': 'Rector de Institución',
                'verbose_name_plural': 'Rectores de Instituciones',
                'db_table': 'facturacion_rector_institucion',
                'ordering': ['institucion__nombre_institucion'],
            },
        ),
    ]
