# Generated by Django 5.2.5 on 2026-03-10 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutricion', '0041_equivalencia_icbf_por_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorPreparacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_preparacion', models.CharField(max_length=255, verbose_name='Nombre de la Preparación')),
                ('estado_validacion', models.CharField(choices=[('valida', 'Válida'), ('con_duda', 'Con Duda'), ('invalida', 'Inválida')], default='valida', max_length=20, verbose_name='Estado de Validación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('componente_sugerido', models.ForeignKey(blank=True, db_column='id_componente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutricion.componentesalimentos', verbose_name='Componente Sugerido')),
            ],
            options={
                'verbose_name': 'Borrador Preparación IA',
                'verbose_name_plural': 'Borradores Preparaciones IA',
                'db_table': 'agente_borrador_preparacion_ia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BorradorIngredienteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_icbf_sugerido', models.CharField(max_length=20, verbose_name='Código ICBF Sugerido')),
                ('nombre_sugerido', models.CharField(max_length=200, verbose_name='Nombre Sugerido')),
                ('estado_validacion', models.CharField(choices=[('valido', 'Válido'), ('no_encontrado', 'No encontrado en catálogo')], default='valido', max_length=20, verbose_name='Estado de Validación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('alimento_icbf', models.ForeignKey(blank=True, db_column='codigo_icbf_resuelto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutricion.tablaalimentos2018icbf', verbose_name='Alimento ICBF Resuelto')),
                ('borrador_preparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='agente.borradorpreparacionia', verbose_name='Preparación del Borrador')),
            ],
            options={
                'verbose_name': 'Borrador Ingrediente IA',
                'verbose_name_plural': 'Borradores Ingredientes IA',
                'db_table': 'agente_borrador_ingrediente_ia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeneracionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_llm', models.CharField(default='gemini-2.0-flash', max_length=100, verbose_name='Modelo LLM')),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('pendiente_revision', 'Pendiente de Revisión'), ('aprobado', 'Aprobado'), ('descartado', 'Descartado'), ('error', 'Error')], default='procesando', max_length=30, verbose_name='Estado')),
                ('prompt_final', models.TextField(blank=True, verbose_name='Prompt Enviado')),
                ('respuesta_cruda', models.TextField(blank=True, verbose_name='Respuesta Cruda del LLM')),
                ('errores_validacion', models.JSONField(blank=True, default=list, verbose_name='Errores de Validación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('id_menu', models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.CASCADE, related_name='generaciones_ia', to='nutricion.tablamenus', verbose_name='Menú')),
                ('usuario_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borradores_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Aprobador')),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generaciones_ia_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'Generación IA',
                'verbose_name_plural': 'Generaciones IA',
                'db_table': 'agente_generacion_ia',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='borradorpreparacionia',
            name='generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparaciones', to='agente.generacionia', verbose_name='Generación'),
        ),
    ]
