# Generated by Django 5.2.5 on 2026-03-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0003_generacion_ia_ocasion_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borradorpreparacionia',
            name='procedimiento',
            field=models.TextField(blank=True, verbose_name='Procedimiento de Preparación'),
        ),
    ]
