# Generated by Django 5.2.5 on 2026-03-21 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0004_add_procedimiento_to_borrador_preparacion'),
        ('principal', '0011_renombrar_ids_niveles_pae'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generacionia',
            name='estado',
            field=models.CharField(choices=[('procesando', 'Procesando'), ('disponible_pool', 'Disponible en Pool'), ('pendiente_revision', 'Pendiente de Revisión'), ('aprobado', 'Aprobado'), ('descartado', 'Descartado'), ('error', 'Error')], default='procesando', max_length=30, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='LoteGeneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocasion_especial', models.CharField(blank=True, max_length=100)),
                ('cantidad_total', models.PositiveIntegerField()),
                ('cantidad_procesada', models.PositiveIntegerField(default=0)),
                ('cantidad_exitosa', models.PositiveIntegerField(default=0)),
                ('cantidad_fallida', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=20)),
                ('resultados', models.JSONField(default=list)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.modalidadesdeconsumo', verbose_name='Modalidad')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_generacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lote de Generación',
                'verbose_name_plural': 'Lotes de Generación',
                'db_table': 'agente_lote_generacion',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
