# Generated by Django 5.2.5 on 2026-02-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planeacion', '0004_add_item_to_sedes_educativas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Ruta')),
            ],
            options={
                'verbose_name': 'Tipo de Ruta',
                'verbose_name_plural': 'Tipos de Rutas',
                'db_table': 'logistica_tipos_rutas',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=100, verbose_name='Nombre de la Ruta')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeacion.programa', verbose_name='Programa/Contrato')),
                ('id_tipo_ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.tiporuta', verbose_name='Tipo de Ruta')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'logistica_rutas',
                'unique_together': {('nombre_ruta', 'id_programa', 'id_tipo_ruta')},
            },
        ),
        migrations.CreateModel(
            name='RutaSedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_visita', models.PositiveIntegerField(default=1, help_text='Ej: 1er colegio, 2do colegio...', verbose_name='Orden de visita')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.ruta', verbose_name='Ruta')),
                ('sede_educativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeacion.sedeseducativas', verbose_name='Sede Educativa')),
            ],
            options={
                'verbose_name': 'Sede en Ruta',
                'verbose_name_plural': 'Sedes en Rutas',
                'db_table': 'logistica_ruta_sedes',
                'ordering': ['id_ruta', 'orden_visita'],
            },
        ),
    ]
