# Generated by Django 5.2.5 on 2026-02-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planeacion', '0001_initial'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruposAlimentos',
            fields=[
                ('id_grupo_alimentos', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Grupo Alimentos')),
                ('grupo_alimentos', models.CharField(max_length=100, verbose_name='Grupo de Alimentos')),
            ],
            options={
                'verbose_name': 'Grupo de Alimento',
                'verbose_name_plural': 'Grupos de Alimentos',
                'db_table': 'grupos_alimentos',
                'ordering': ['id_grupo_alimentos'],
            },
        ),
        migrations.CreateModel(
            name='PermisosNutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Permisos de Nutrición',
                'permissions': [('view_contenido_nutricion', 'Puede ver el contenido del módulo de nutrición')],
            },
        ),
        migrations.CreateModel(
            name='TablaAlimentos2018Icbf',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre_del_alimento', models.CharField(max_length=200, verbose_name='Nombre del Alimento')),
                ('parte_analizada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parte Analizada')),
                ('humedad_g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Humedad (g)')),
                ('energia_kcal', models.IntegerField(verbose_name='Energía (kcal)')),
                ('energia_kj', models.IntegerField(verbose_name='Energía (kJ)')),
                ('proteina_g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Proteína (g)')),
                ('lipidos_g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lípidos (g)')),
                ('carbohidratos_totales_g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Carbohidratos Totales (g)')),
                ('carbohidratos_disponibles_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Carbohidratos Disponibles (g)')),
                ('fibra_dietaria_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fibra Dietaria (g)')),
                ('cenizas_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cenizas (g)')),
                ('calcio_mg', models.IntegerField(blank=True, null=True, verbose_name='Calcio (mg)')),
                ('hierro_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hierro (mg)')),
                ('sodio_mg', models.IntegerField(blank=True, null=True, verbose_name='Sodio (mg)')),
                ('fosforo_mg', models.IntegerField(blank=True, null=True, verbose_name='Fósforo (mg)')),
                ('yodo_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yodo (mg)')),
                ('zinc_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zinc (mg)')),
                ('magnesio_mg', models.IntegerField(blank=True, null=True, verbose_name='Magnesio (mg)')),
                ('potasio_mg', models.IntegerField(blank=True, null=True, verbose_name='Potasio (mg)')),
                ('tiamina_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiamina (mg)')),
                ('riboflavina_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Riboflavina (mg)')),
                ('niacina_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Niacina (mg)')),
                ('folatos_mcg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Folatos (mcg)')),
                ('vitamina_b12_mcg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vitamina B12 (mcg)')),
                ('vitamina_c_mg', models.IntegerField(blank=True, null=True, verbose_name='Vitamina C (mg)')),
                ('vitamina_a_er', models.IntegerField(blank=True, null=True, verbose_name='Vitamina A (ER)')),
                ('grasa_saturada_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Grasa Saturada (g)')),
                ('grasa_monoinsaturada_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Grasa Monoinsaturada (g)')),
                ('grasa_poliinsaturada_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Grasa Poliinsaturada (g)')),
                ('colesterol_mg', models.IntegerField(blank=True, null=True, verbose_name='Colesterol (mg)')),
                ('parte_comestible_field', models.IntegerField(blank=True, db_column='parte_comestible_porcentaje', null=True, verbose_name='Parte Comestible (%)')),
            ],
            options={
                'verbose_name': 'Alimento ICBF 2018',
                'verbose_name_plural': 'Alimentos ICBF 2018',
                'db_table': 'TABLA_ALIMENTOS_2018_ICBF',
                'ordering': ['nombre_del_alimento'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TablaIngredientesSiesa',
            fields=[
                ('id_ingrediente_siesa', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código del Ingrediente')),
                ('nombre_ingrediente', models.CharField(max_length=255, verbose_name='Nombre del Ingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente de Inventario',
                'verbose_name_plural': 'Ingredientes de Inventario',
                'db_table': 'tabla_ingredientes_siesa',
                'ordering': ['nombre_ingrediente'],
            },
        ),
        migrations.CreateModel(
            name='ComponentesAlimentos',
            fields=[
                ('id_componente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Componente')),
                ('componente', models.CharField(max_length=100, verbose_name='Componente')),
                ('id_grupo_alimentos', models.ForeignKey(db_column='id_grupo_alimentos', on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='nutricion.gruposalimentos', verbose_name='Grupo de Alimentos')),
            ],
            options={
                'verbose_name': 'Componente de Alimento',
                'verbose_name_plural': 'Componentes de Alimentos',
                'db_table': 'componentes_alimentos',
                'ordering': ['componente'],
            },
        ),
        migrations.CreateModel(
            name='TablaMenus',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Menú')),
                ('menu', models.CharField(max_length=255, verbose_name='Nombre del Menú')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('id_contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='planeacion.programa', verbose_name='Programa/Contrato')),
                ('id_modalidad', models.ForeignKey(db_column='id_modalidad', on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='principal.modalidadesdeconsumo', verbose_name='Modalidad de Consumo')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'db_table': 'tabla_menus',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TablaAnalisisNutricionalMenu',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Análisis')),
                ('total_calorias', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Calorías (kcal)')),
                ('total_proteina', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Proteína (g)')),
                ('total_grasa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Grasa (g)')),
                ('total_cho', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total CHO (g)')),
                ('total_calcio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Calcio (mg)')),
                ('total_hierro', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Hierro (mg)')),
                ('total_sodio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Sodio (mg)')),
                ('total_peso_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Peso Neto (g)')),
                ('total_peso_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Peso Bruto (g)')),
                ('porcentaje_calorias', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Calorías')),
                ('porcentaje_proteina', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Proteína')),
                ('porcentaje_grasa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Grasa')),
                ('porcentaje_cho', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación CHO')),
                ('porcentaje_calcio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Calcio')),
                ('porcentaje_hierro', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Hierro')),
                ('porcentaje_sodio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Sodio')),
                ('estado_calorias', models.CharField(default='optimo', max_length=20, verbose_name='Estado Calorías')),
                ('estado_proteina', models.CharField(default='optimo', max_length=20, verbose_name='Estado Proteína')),
                ('estado_grasa', models.CharField(default='optimo', max_length=20, verbose_name='Estado Grasa')),
                ('estado_cho', models.CharField(default='optimo', max_length=20, verbose_name='Estado CHO')),
                ('estado_calcio', models.CharField(default='optimo', max_length=20, verbose_name='Estado Calcio')),
                ('estado_hierro', models.CharField(default='optimo', max_length=20, verbose_name='Estado Hierro')),
                ('estado_sodio', models.CharField(default='optimo', max_length=20, verbose_name='Estado Sodio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que Modificó')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas u Observaciones')),
                ('id_nivel_escolar_uapa', models.ForeignKey(db_column='id_nivel_escolar_uapa', on_delete=django.db.models.deletion.PROTECT, related_name='analisis_nutricionales', to='principal.tablagradosescolaresuapa', verbose_name='Nivel Escolar UAPA')),
                ('id_menu', models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.CASCADE, related_name='analisis_nutricionales', to='nutricion.tablamenus', verbose_name='Menú')),
            ],
            options={
                'verbose_name': 'Análisis Nutricional de Menú',
                'verbose_name_plural': 'Análisis Nutricionales de Menús',
                'db_table': 'tabla_analisis_nutricional_menu',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='TablaPreparaciones',
            fields=[
                ('id_preparacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Preparación')),
                ('preparacion', models.CharField(max_length=255, verbose_name='Nombre de la Preparación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('id_componente', models.ForeignKey(blank=True, db_column='id_componente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones', to='nutricion.componentesalimentos', verbose_name='Componente de Alimento')),
                ('id_menu', models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.CASCADE, related_name='preparaciones', to='nutricion.tablamenus', verbose_name='Menú')),
            ],
            options={
                'verbose_name': 'Preparación/Receta',
                'verbose_name_plural': 'Preparaciones/Recetas',
                'db_table': 'tabla_preparaciones',
                'ordering': ['preparacion'],
            },
        ),
        migrations.CreateModel(
            name='TablaIngredientesPorNivel',
            fields=[
                ('id_ingrediente_nivel', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Ingrediente Nivel')),
                ('peso_neto', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Peso Neto (g)')),
                ('peso_bruto', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Peso Bruto (g)')),
                ('parte_comestible', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='% Parte Comestible')),
                ('calorias', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Calorías (kcal)')),
                ('proteina', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Proteína (g)')),
                ('grasa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Grasa (g)')),
                ('cho', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CHO (g)')),
                ('calcio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Calcio (mg)')),
                ('hierro', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hierro (mg)')),
                ('sodio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sodio (mg)')),
                ('codigo_icbf', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código ICBF')),
                ('id_analisis', models.ForeignKey(db_column='id_analisis', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_configurados', to='nutricion.tablaanalisisnutricionalmenu', verbose_name='Análisis Nutricional')),
                ('id_ingrediente_siesa', models.ForeignKey(db_column='id_ingrediente_siesa', on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_por_nivel', to='nutricion.tablaingredientessiesa', verbose_name='Ingrediente')),
                ('id_preparacion', models.ForeignKey(db_column='id_preparacion', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_por_nivel', to='nutricion.tablapreparaciones', verbose_name='Preparación')),
            ],
            options={
                'verbose_name': 'Ingrediente Configurado por Nivel',
                'verbose_name_plural': 'Ingredientes Configurados por Nivel',
                'db_table': 'tabla_ingredientes_por_nivel',
                'ordering': ['id_preparacion', 'id_ingrediente_siesa'],
            },
        ),
        migrations.CreateModel(
            name='TablaPreparacionIngredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ingrediente_siesa', models.ForeignKey(db_column='id_ingrediente_siesa', on_delete=django.db.models.deletion.CASCADE, related_name='preparaciones', to='nutricion.tablaingredientessiesa', verbose_name='Ingrediente')),
                ('id_preparacion', models.ForeignKey(db_column='id_preparacion', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='nutricion.tablapreparaciones', verbose_name='Preparación')),
            ],
            options={
                'verbose_name': 'Ingrediente de Preparación',
                'verbose_name_plural': 'Ingredientes de Preparaciones',
                'db_table': 'tabla_preparacion_ingredientes',
                'ordering': ['id_preparacion__preparacion', 'id_ingrediente_siesa__nombre_ingrediente'],
            },
        ),
        migrations.CreateModel(
            name='TablaRequerimientosNutricionales',
            fields=[
                ('id_requerimiento_nutricional', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Requerimiento')),
                ('calorias_kcal', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Calorías (Kcal)')),
                ('proteina_g', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Proteína (g)')),
                ('grasa_g', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Grasa (g)')),
                ('cho_g', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='CHO (g)')),
                ('calcio_mg', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Calcio (mg)')),
                ('hierro_mg', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Hierro (mg)')),
                ('sodio_mg', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Sodio (mg)')),
                ('id_nivel_escolar_uapa', models.ForeignKey(db_column='id_nivel_escolar_uapa', on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_nutricionales', to='principal.tablagradosescolaresuapa', verbose_name='Nivel Escolar UAPA')),
            ],
            options={
                'verbose_name': 'Requerimiento Nutricional',
                'verbose_name_plural': 'Requerimientos Nutricionales',
                'db_table': 'tabla_requerimientos_nutricionales',
                'ordering': ['id_nivel_escolar_uapa'],
            },
        ),
        migrations.AddIndex(
            model_name='tablamenus',
            index=models.Index(fields=['id_modalidad'], name='tabla_menus_id_moda_e67821_idx'),
        ),
        migrations.AddIndex(
            model_name='tablamenus',
            index=models.Index(fields=['id_contrato'], name='tabla_menus_id_cont_48674c_idx'),
        ),
        migrations.AddIndex(
            model_name='tablaanalisisnutricionalmenu',
            index=models.Index(fields=['id_menu'], name='tabla_anali_id_menu_bcf7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='tablaanalisisnutricionalmenu',
            index=models.Index(fields=['id_nivel_escolar_uapa'], name='tabla_anali_id_nive_5d123c_idx'),
        ),
        migrations.AddIndex(
            model_name='tablaanalisisnutricionalmenu',
            index=models.Index(fields=['fecha_actualizacion'], name='tabla_anali_fecha_a_914f64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablaanalisisnutricionalmenu',
            unique_together={('id_menu', 'id_nivel_escolar_uapa')},
        ),
        migrations.AddIndex(
            model_name='tablaingredientespornivel',
            index=models.Index(fields=['id_analisis'], name='tabla_ingre_id_anal_e041b2_idx'),
        ),
        migrations.AddIndex(
            model_name='tablaingredientespornivel',
            index=models.Index(fields=['id_preparacion'], name='tabla_ingre_id_prep_956161_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablaingredientespornivel',
            unique_together={('id_analisis', 'id_preparacion', 'id_ingrediente_siesa')},
        ),
        migrations.AddIndex(
            model_name='tablapreparacioningredientes',
            index=models.Index(fields=['id_preparacion'], name='tabla_prepa_id_prep_bd442d_idx'),
        ),
        migrations.AddIndex(
            model_name='tablapreparacioningredientes',
            index=models.Index(fields=['id_ingrediente_siesa'], name='tabla_prepa_id_ingr_f3b3fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablapreparacioningredientes',
            unique_together={('id_preparacion', 'id_ingrediente_siesa')},
        ),
        migrations.AlterUniqueTogether(
            name='tablarequerimientosnutricionales',
            unique_together={('id_nivel_escolar_uapa',)},
        ),
    ]
