# Generated by Django 5.2.5 on 2025-08-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosNutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Permisos de Nutrición',
                'permissions': [('view_contenido_nutricion', 'Puede ver el contenido del módulo de nutrición')],
            },
        ),
    ]
