# Generated by Django 5.2.5 on 2025-09-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaAlimentos2018Icbf',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_del_alimento', models.CharField(max_length=200)),
                ('parte_analizada', models.CharField(blank=True, max_length=100, null=True)),
                ('humedad_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energia_kcal', models.IntegerField()),
                ('energia_kj', models.IntegerField()),
                ('proteina_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lipidos_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbohidratos_totales_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbohidratos_disponibles_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fibra_dietaria_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cenizas_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calcio_mg', models.IntegerField(blank=True, null=True)),
                ('hierro_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodio_mg', models.IntegerField(blank=True, null=True)),
                ('fosforo_mg', models.IntegerField(blank=True, null=True)),
                ('yodo_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zinc_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('magnesio_mg', models.IntegerField(blank=True, null=True)),
                ('potasio_mg', models.IntegerField(blank=True, null=True)),
                ('tiamina_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('riboflavina_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('niacina_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('folatos_mcg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vitamina_b12_mcg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vitamina_c_mg', models.IntegerField(blank=True, null=True)),
                ('vitamina_a_er', models.IntegerField(blank=True, null=True)),
                ('grasa_saturada_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grasa_monoinsaturada_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grasa_poliinsaturada_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('colesterol_mg', models.IntegerField(blank=True, null=True)),
                ('parte_comestible_field', models.IntegerField(blank=True, db_column='parte_comestible_porcentaje', null=True)),
            ],
            options={
                'verbose_name': 'Alimento ICBF 2018',
                'verbose_name_plural': 'Alimentos ICBF 2018',
                'db_table': 'TABLA_ALIMENTOS_2018_ICBF',
                'managed': True,
            },
        ),
    ]
