# Generated by Django 5.2.5 on 2025-10-03 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0002_tablaalimentos2018icbf'),
        ('planeacion', '0012_rename_planificaci_etc_id_8e7a3d_idx_planificaci_id_muni_4996d1_idx_and_more'),
        ('principal', '0008_nivelgradoescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaIngredientesSiesa',
            fields=[
                ('id_ingrediente_siesa', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Ingrediente')),
                ('nombre_ingrediente', models.CharField(max_length=255, verbose_name='Nombre del Ingrediente')),
                ('unidades', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Presentación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Ingrediente de Inventario',
                'verbose_name_plural': 'Ingredientes de Inventario',
                'db_table': 'tabla_ingredientes_siesa',
                'ordering': ['nombre_ingrediente'],
            },
        ),
        migrations.AlterModelOptions(
            name='tablaalimentos2018icbf',
            options={'managed': True, 'ordering': ['nombre_del_alimento'], 'verbose_name': 'Alimento ICBF 2018', 'verbose_name_plural': 'Alimentos ICBF 2018'},
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='calcio_mg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calcio (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='carbohidratos_disponibles_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Carbohidratos Disponibles (g)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='carbohidratos_totales_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Carbohidratos Totales (g)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='cenizas_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cenizas (g)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='colesterol_mg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Colesterol (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='energia_kcal',
            field=models.IntegerField(verbose_name='Energía (kcal)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='energia_kj',
            field=models.IntegerField(verbose_name='Energía (kJ)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='fibra_dietaria_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fibra Dietaria (g)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='folatos_mcg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Folatos (mcg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='fosforo_mg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fósforo (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='grasa_monoinsaturada_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Grasa Monoinsaturada (g)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='grasa_poliinsaturada_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Grasa Poliinsaturada (g)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='grasa_saturada_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Grasa Saturada (g)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='hierro_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hierro (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='humedad_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Humedad (g)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='lipidos_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lípidos (g)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='magnesio_mg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Magnesio (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='niacina_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Niacina (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='nombre_del_alimento',
            field=models.CharField(max_length=200, verbose_name='Nombre del Alimento'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='parte_analizada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parte Analizada'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='parte_comestible_field',
            field=models.IntegerField(blank=True, db_column='parte_comestible_porcentaje', null=True, verbose_name='Parte Comestible (%)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='potasio_mg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Potasio (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='proteina_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Proteína (g)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='riboflavina_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Riboflavina (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='sodio_mg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sodio (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='tiamina_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiamina (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='vitamina_a_er',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vitamina A (ER)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='vitamina_b12_mcg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vitamina B12 (mcg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='vitamina_c_mg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vitamina C (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='yodo_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yodo (mg)'),
        ),
        migrations.AlterField(
            model_name='tablaalimentos2018icbf',
            name='zinc_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zinc (mg)'),
        ),
        migrations.CreateModel(
            name='TablaMenus',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Menú')),
                ('menu', models.CharField(max_length=255, verbose_name='Nombre del Menú')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('id_contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='planeacion.programa', verbose_name='Programa/Contrato')),
                ('id_modalidad', models.ForeignKey(db_column='id_modalidad', on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='principal.modalidadesdeconsumo', verbose_name='Modalidad de Consumo')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'db_table': 'tabla_menus',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TablaPreparaciones',
            fields=[
                ('id_preparacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Preparación')),
                ('preparacion', models.CharField(max_length=255, verbose_name='Nombre de la Preparación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('id_menu', models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.CASCADE, related_name='preparaciones', to='nutricion.tablamenus', verbose_name='Menú')),
            ],
            options={
                'verbose_name': 'Preparación/Receta',
                'verbose_name_plural': 'Preparaciones/Recetas',
                'db_table': 'tabla_preparaciones',
                'ordering': ['preparacion'],
            },
        ),
        migrations.CreateModel(
            name='TablaPreparacionIngredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (kg)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('id_ingrediente_siesa', models.ForeignKey(db_column='id_ingrediente_siesa', on_delete=django.db.models.deletion.CASCADE, related_name='preparaciones', to='nutricion.tablaingredientessiesa', verbose_name='Ingrediente')),
                ('id_preparacion', models.ForeignKey(db_column='id_preparacion', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='nutricion.tablapreparaciones', verbose_name='Preparación')),
            ],
            options={
                'verbose_name': 'Ingrediente de Preparación',
                'verbose_name_plural': 'Ingredientes de Preparaciones',
                'db_table': 'tabla_preparacion_ingredientes',
                'ordering': ['id_preparacion__preparacion', 'id_ingrediente_siesa__nombre_ingrediente'],
            },
        ),
        migrations.AddIndex(
            model_name='tablamenus',
            index=models.Index(fields=['id_modalidad'], name='tabla_menus_id_moda_e67821_idx'),
        ),
        migrations.AddIndex(
            model_name='tablamenus',
            index=models.Index(fields=['id_contrato'], name='tabla_menus_id_cont_48674c_idx'),
        ),
        migrations.AddIndex(
            model_name='tablapreparacioningredientes',
            index=models.Index(fields=['id_preparacion'], name='tabla_prepa_id_prep_bd442d_idx'),
        ),
        migrations.AddIndex(
            model_name='tablapreparacioningredientes',
            index=models.Index(fields=['id_ingrediente_siesa'], name='tabla_prepa_id_ingr_f3b3fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablapreparacioningredientes',
            unique_together={('id_preparacion', 'id_ingrediente_siesa')},
        ),
    ]
