# Generated by Django 5.2.5 on 2025-10-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0003_tablaingredientessiesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaingredientessiesa',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='tablaingredientessiesa',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='tablaingredientessiesa',
            name='unidades',
        ),
        migrations.RemoveField(
            model_name='tablapreparacioningredientes',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='tablaingredientessiesa',
            name='id_ingrediente_siesa',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código del Ingrediente'),
        ),
    ]
