# Generated by Django 5.2.5 on 2025-10-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0004_remove_tablaingredientessiesa_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablapreparacioningredientes',
            name='cantidad',
        ),
    ]
