# Generated by Django 5.2.5 on 2025-10-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0005_remove_tablapreparacioningredientes_cantidad'),
        ('principal', '0011_alter_nivelgradoescolar_nivel_escolar_uapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaRequerimientosNutricionales',
            fields=[
                ('id_requerimiento_nutricional', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Requerimiento')),
                ('calorias_kcal', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Calorías (Kcal)')),
                ('proteina_g', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Proteína (g)')),
                ('grasa_g', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Grasa (g)')),
                ('cho_g', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='CHO (g)')),
                ('calcio_mg', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Calcio (mg)')),
                ('hierro_mg', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Hierro (mg)')),
                ('sodio_mg', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Sodio (mg)')),
                ('id_nivel_escolar_uapa', models.ForeignKey(db_column='id_nivel_escolar_uapa', on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_nutricionales', to='principal.tablagradosescolaresuapa', verbose_name='Nivel Escolar UAPA')),
            ],
            options={
                'verbose_name': 'Requerimiento Nutricional',
                'verbose_name_plural': 'Requerimientos Nutricionales',
                'db_table': 'tabla_requerimientos_nutricionales',
                'ordering': ['id_nivel_escolar_uapa'],
                'unique_together': {('id_nivel_escolar_uapa',)},
            },
        ),
    ]
