# Generated by Django 5.2.5 on 2025-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0006_tablarequerimientosnutricionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablarequerimientosnutricionales',
            name='id_requerimiento_nutricional',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Requerimiento'),
        ),
    ]
