# Generated by Django 5.2.5 on 2025-10-04 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0007_alter_tablarequerimientosnutricionales_id_requerimiento_nutricional'),
        ('principal', '0011_alter_nivelgradoescolar_nivel_escolar_uapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaAnalisisNutricionalMenu',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Análisis')),
                ('total_calorias', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Calorías (kcal)')),
                ('total_proteina', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Proteína (g)')),
                ('total_grasa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Grasa (g)')),
                ('total_cho', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total CHO (g)')),
                ('total_calcio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Calcio (mg)')),
                ('total_hierro', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Hierro (mg)')),
                ('total_sodio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Sodio (mg)')),
                ('total_peso_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Peso Neto (g)')),
                ('total_peso_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Peso Bruto (g)')),
                ('porcentaje_calorias', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Calorías')),
                ('porcentaje_proteina', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Proteína')),
                ('porcentaje_grasa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Grasa')),
                ('porcentaje_cho', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación CHO')),
                ('porcentaje_calcio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Calcio')),
                ('porcentaje_hierro', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Hierro')),
                ('porcentaje_sodio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Adecuación Sodio')),
                ('estado_calorias', models.CharField(default='optimo', max_length=20, verbose_name='Estado Calorías')),
                ('estado_proteina', models.CharField(default='optimo', max_length=20, verbose_name='Estado Proteína')),
                ('estado_grasa', models.CharField(default='optimo', max_length=20, verbose_name='Estado Grasa')),
                ('estado_cho', models.CharField(default='optimo', max_length=20, verbose_name='Estado CHO')),
                ('estado_calcio', models.CharField(default='optimo', max_length=20, verbose_name='Estado Calcio')),
                ('estado_hierro', models.CharField(default='optimo', max_length=20, verbose_name='Estado Hierro')),
                ('estado_sodio', models.CharField(default='optimo', max_length=20, verbose_name='Estado Sodio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que Modificó')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas u Observaciones')),
                ('id_menu', models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.CASCADE, related_name='analisis_nutricionales', to='nutricion.tablamenus', verbose_name='Menú')),
                ('id_nivel_escolar_uapa', models.ForeignKey(db_column='id_nivel_escolar_uapa', on_delete=django.db.models.deletion.PROTECT, related_name='analisis_nutricionales', to='principal.tablagradosescolaresuapa', verbose_name='Nivel Escolar UAPA')),
            ],
            options={
                'verbose_name': 'Análisis Nutricional de Menú',
                'verbose_name_plural': 'Análisis Nutricionales de Menús',
                'db_table': 'tabla_analisis_nutricional_menu',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='TablaIngredientesPorNivel',
            fields=[
                ('id_ingrediente_nivel', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Ingrediente Nivel')),
                ('peso_neto', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Peso Neto (g)')),
                ('peso_bruto', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Peso Bruto (g)')),
                ('parte_comestible', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='% Parte Comestible')),
                ('calorias', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Calorías (kcal)')),
                ('proteina', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Proteína (g)')),
                ('grasa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Grasa (g)')),
                ('cho', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CHO (g)')),
                ('calcio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Calcio (mg)')),
                ('hierro', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hierro (mg)')),
                ('sodio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sodio (mg)')),
                ('codigo_icbf', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código ICBF')),
                ('id_analisis', models.ForeignKey(db_column='id_analisis', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_configurados', to='nutricion.tablaanalisisnutricionalmenu', verbose_name='Análisis Nutricional')),
                ('id_ingrediente_siesa', models.ForeignKey(db_column='id_ingrediente_siesa', on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_por_nivel', to='nutricion.tablaingredientessiesa', verbose_name='Ingrediente')),
                ('id_preparacion', models.ForeignKey(db_column='id_preparacion', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_por_nivel', to='nutricion.tablapreparaciones', verbose_name='Preparación')),
            ],
            options={
                'verbose_name': 'Ingrediente Configurado por Nivel',
                'verbose_name_plural': 'Ingredientes Configurados por Nivel',
                'db_table': 'tabla_ingredientes_por_nivel',
                'ordering': ['id_preparacion', 'id_ingrediente_siesa'],
            },
        ),
        migrations.AddIndex(
            model_name='tablaanalisisnutricionalmenu',
            index=models.Index(fields=['id_menu'], name='tabla_anali_id_menu_bcf7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='tablaanalisisnutricionalmenu',
            index=models.Index(fields=['id_nivel_escolar_uapa'], name='tabla_anali_id_nive_5d123c_idx'),
        ),
        migrations.AddIndex(
            model_name='tablaanalisisnutricionalmenu',
            index=models.Index(fields=['fecha_actualizacion'], name='tabla_anali_fecha_a_914f64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablaanalisisnutricionalmenu',
            unique_together={('id_menu', 'id_nivel_escolar_uapa')},
        ),
        migrations.AddIndex(
            model_name='tablaingredientespornivel',
            index=models.Index(fields=['id_analisis'], name='tabla_ingre_id_anal_e041b2_idx'),
        ),
        migrations.AddIndex(
            model_name='tablaingredientespornivel',
            index=models.Index(fields=['id_preparacion'], name='tabla_ingre_id_prep_956161_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablaingredientespornivel',
            unique_together={('id_analisis', 'id_preparacion', 'id_ingrediente_siesa')},
        ),
    ]
