# Generated by Django 5.2.5 on 2025-10-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0008_tablaanalisisnutricionalmenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruposAlimentos',
            fields=[
                ('id_grupo_alimentos', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Grupo Alimentos')),
                ('grupo_alimentos', models.CharField(max_length=100, verbose_name='Grupo de Alimentos')),
            ],
            options={
                'verbose_name': 'Grupo de Alimento',
                'verbose_name_plural': 'Grupos de Alimentos',
                'db_table': 'grupos_alimentos',
                'ordering': ['id_grupo_alimentos'],
            },
        ),
        migrations.CreateModel(
            name='ComponentesAlimentos',
            fields=[
                ('id_componente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Componente')),
                ('componente', models.CharField(max_length=100, verbose_name='Componente')),
                ('id_grupo_alimentos', models.ForeignKey(db_column='id_grupo_alimentos', on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='nutricion.gruposalimentos', verbose_name='Grupo de Alimentos')),
            ],
            options={
                'verbose_name': 'Componente de Alimento',
                'verbose_name_plural': 'Componentes de Alimentos',
                'db_table': 'componentes_alimentos',
                'ordering': ['componente'],
            },
        ),
    ]
