# Generated by Django 5.2.5 on 2025-10-09 15:23

from django.db import migrations

def populate_grupos_alimentos(apps, schema_editor):
    GruposAlimentos = apps.get_model('nutricion', 'GruposAlimentos')
    grupos_data = [
        ('g1', 'Grupo I. Cereales, raíces, tubérculos y plátanos'),
        ('g2', 'Grupo II. Fruta y verduras'),
        ('g3', 'Grupo III. Leche y productos lácteos'),
        ('g4', 'Grupo IV. Carnes, huevos, leguminosas secas, frutos secos y semillas'),
        ('g5', 'Grupo V. Grasas'),
        ('g6', 'Grupo VI. Azúcares'),
    ]
    for id_grupo, grupo in grupos_data:
        GruposAlimentos.objects.get_or_create(id_grupo_alimentos=id_grupo, defaults={'grupo_alimentos': grupo})

def populate_componentes_alimentos(apps, schema_editor):
    ComponentesAlimentos = apps.get_model('nutricion', 'ComponentesAlimentos')
    GruposAlimentos = apps.get_model('nutricion', 'GruposAlimentos')
    componentes_data = [
        ('com1', 'Bebida con leche', 'g3'),
        ('com2', 'Alimento proteico', 'g4'),
        ('com3', 'Cereal acompañante', 'g1'),
        ('com4', 'Fruta', 'g2'),
        ('com5', 'Azúcares', 'g6'),
        ('com6', 'Grasas', 'g5'),
        ('com7', 'Cereales', 'g1'),
        ('com8', 'Tuberculos, raíces, plátanos y derivados de cereal', 'g1'),
        ('com9', 'Ensalada o verdura caliente', 'g2'),
        ('com10', 'Bebida láctea y productos lácteos', 'g3'),
        ('com11', 'Leche y productos lácteos', 'g3'),
        ('com12', 'Frutas', 'g2'),
        ('com13', 'Postre', 'g4'),
    ]
    for id_comp, comp, id_grupo in componentes_data:
        grupo = GruposAlimentos.objects.get(id_grupo_alimentos=id_grupo)
        ComponentesAlimentos.objects.get_or_create(id_componente=id_comp, defaults={'componente': comp, 'id_grupo_alimentos': grupo})

class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0009_gruposalimentos_componentesalimentos'),
    ]

    operations = [
        migrations.RunPython(populate_grupos_alimentos),
        migrations.RunPython(populate_componentes_alimentos),
    ]