# Generated by Django 5.2.5 on 2025-10-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0010_populate_grupos_componentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablapreparaciones',
            name='id_componente',
            field=models.ForeignKey(blank=True, db_column='id_componente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones', to='nutricion.componentesalimentos', verbose_name='Componente de Alimento'),
        ),
    ]
