# Generated by Django 5.2.5 on 2026-02-13 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0012_adecuacion_total_porcentaje'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutaPatronMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_neto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Neto Mínimo (g)')),
                ('peso_neto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Neto Máximo (g)')),
            ],
            options={
                'verbose_name': 'Meta de Minuta Patrón',
                'verbose_name_plural': 'Metas de Minuta Patrón',
                'db_table': 'nutricion_minuta_patron_rangos',
            },
        ),
        migrations.RenameIndex(
            model_name='requerimientosemanal',
            new_name='nutricion_r_modalid_4d33e5_idx',
            old_name='nutricion_r_modalid_idx',
        ),
        migrations.RenameIndex(
            model_name='requerimientosemanal',
            new_name='nutricion_r_compone_f7553a_idx',
            old_name='nutricion_r_compone_idx',
        ),
        migrations.RenameIndex(
            model_name='tablaanalisisnutricionalmenu',
            new_name='nutricion_t_id_menu_238f16_idx',
            old_name='tabla_anali_id_menu_bcf7b7_idx',
        ),
        migrations.RenameIndex(
            model_name='tablaanalisisnutricionalmenu',
            new_name='nutricion_t_id_nive_dfab5f_idx',
            old_name='tabla_anali_id_nive_5d123c_idx',
        ),
        migrations.RenameIndex(
            model_name='tablaanalisisnutricionalmenu',
            new_name='nutricion_t_fecha_a_c18ce0_idx',
            old_name='tabla_anali_fecha_a_914f64_idx',
        ),
        migrations.RenameIndex(
            model_name='tablaingredientespornivel',
            new_name='nutricion_t_id_anal_0f0ae1_idx',
            old_name='tabla_ingre_id_anal_e041b2_idx',
        ),
        migrations.RenameIndex(
            model_name='tablaingredientespornivel',
            new_name='nutricion_t_id_prep_8507ab_idx',
            old_name='tabla_ingre_id_prep_956161_idx',
        ),
        migrations.RenameIndex(
            model_name='tablamenus',
            new_name='nutricion_t_id_moda_1ce448_idx',
            old_name='tabla_menus_id_moda_e67821_idx',
        ),
        migrations.RenameIndex(
            model_name='tablamenus',
            new_name='nutricion_t_id_cont_4a3abe_idx',
            old_name='tabla_menus_id_cont_48674c_idx',
        ),
        migrations.RenameIndex(
            model_name='tablapreparacioningredientes',
            new_name='nutricion_t_id_prep_6daa72_idx',
            old_name='tabla_prepa_id_prep_bd442d_idx',
        ),
        migrations.RenameIndex(
            model_name='tablapreparacioningredientes',
            new_name='nutricion_t_id_ingr_65d26d_idx',
            old_name='tabla_prepa_id_ingr_f3b3fa_idx',
        ),
        migrations.AlterField(
            model_name='adecuaciontotalporcentaje',
            name='id_modalidad',
            field=models.ForeignKey(blank=True, db_column='id_modalidad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adecuaciones_porcentaje', to='principal.modalidadesdeconsumo', verbose_name='Modalidad de Consumo'),
        ),
        migrations.AddField(
            model_name='minutapatronmeta',
            name='id_componente',
            field=models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.CASCADE, related_name='metas_minuta', to='nutricion.componentesalimentos', verbose_name='Componente de Alimento'),
        ),
        migrations.AddField(
            model_name='minutapatronmeta',
            name='id_grado_escolar_uapa',
            field=models.ForeignKey(db_column='id_grado_escolar_uapa', on_delete=django.db.models.deletion.CASCADE, related_name='metas_minuta', to='principal.tablagradosescolaresuapa', verbose_name='Grado Escolar UAPA'),
        ),
        migrations.AddField(
            model_name='minutapatronmeta',
            name='id_grupo_alimentos',
            field=models.ForeignKey(db_column='id_grupo_alimentos', on_delete=django.db.models.deletion.CASCADE, related_name='metas_minuta', to='nutricion.gruposalimentos', verbose_name='Grupo de Alimentos'),
        ),
        migrations.AddField(
            model_name='minutapatronmeta',
            name='id_modalidad',
            field=models.ForeignKey(db_column='id_modalidad', on_delete=django.db.models.deletion.CASCADE, related_name='metas_minuta', to='principal.modalidadesdeconsumo', verbose_name='Modalidad de Consumo'),
        ),
        migrations.AlterUniqueTogether(
            name='minutapatronmeta',
            unique_together={('id_modalidad', 'id_grado_escolar_uapa', 'id_componente', 'id_grupo_alimentos')},
        ),
    ]
