# Generated by Django 5.2.5 on 2026-02-13 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0013_minutapatronmeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaalimentos2018icbf',
            name='id_componente',
            field=models.ForeignKey(blank=True, db_column='id_componente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alimentos_icbf', to='nutricion.componentesalimentos', verbose_name='Componente de Alimento'),
        ),
        migrations.AlterModelTable(
            name='tablaalimentos2018icbf',
            table='nutricion_tabla_alimentos_2018_icb',
        ),
    ]
