# Generated by Codex on 2026-02-14

import django.db.models.deletion
from django.db import migrations, models, transaction


def mapear_relaciones_siesa_a_icbf(apps, schema_editor):
    TablaPreparacionIngredientes = apps.get_model('nutricion', 'TablaPreparacionIngredientes')
    TablaIngredientesSiesa = apps.get_model('nutricion', 'TablaIngredientesSiesa')
    TablaAlimentos2018Icbf = apps.get_model('nutricion', 'TablaAlimentos2018Icbf')

    with transaction.atomic():
        relaciones = list(
            TablaPreparacionIngredientes.objects.order_by().values(
                'id_preparacion_id',
                'id_ingrediente_siesa_id',
            )
        )

        for rel in relaciones:
            id_preparacion = rel['id_preparacion_id']
            codigo_actual = rel['id_ingrediente_siesa_id']

            # 1) Match directo por código
            objetivo = TablaAlimentos2018Icbf.objects.filter(codigo=codigo_actual).first()

            # 2) Match por nombre del SIESA -> ICBF
            if not objetivo:
                ing_siesa = TablaIngredientesSiesa.objects.filter(
                    id_ingrediente_siesa=codigo_actual
                ).first()

                if ing_siesa and ing_siesa.nombre_ingrediente:
                    nombre = ing_siesa.nombre_ingrediente.strip()
                    objetivo = (
                        TablaAlimentos2018Icbf.objects.filter(
                            nombre_del_alimento__iexact=nombre
                        ).first()
                        or TablaAlimentos2018Icbf.objects.filter(
                            nombre_del_alimento__icontains=nombre
                        ).first()
                    )

            # Si no se pudo mapear, eliminamos la relación no mapeable
            if not objetivo:
                TablaPreparacionIngredientes.objects.filter(
                    id_preparacion_id=id_preparacion,
                    id_ingrediente_siesa_id=codigo_actual
                ).delete()
                continue

            # Si ya existe la relación destino, eliminamos duplicado origen
            ya_existe = TablaPreparacionIngredientes.objects.filter(
                id_preparacion_id=id_preparacion,
                id_ingrediente_siesa_id=objetivo.codigo
            ).exists()

            if ya_existe:
                TablaPreparacionIngredientes.objects.filter(
                    id_preparacion_id=id_preparacion,
                    id_ingrediente_siesa_id=codigo_actual
                ).delete()
                continue

            # Reasignar FK al código ICBF mapeado
            TablaPreparacionIngredientes.objects.filter(
                id_preparacion_id=id_preparacion,
                id_ingrediente_siesa_id=codigo_actual
            ).update(id_ingrediente_siesa_id=objetivo.codigo)


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0014_tablaalimentos2018icbf_id_componente_and_more'),
    ]

    operations = [
        migrations.RunPython(
            mapear_relaciones_siesa_a_icbf,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='tablapreparacioningredientes',
            name='id_ingrediente_siesa',
            field=models.ForeignKey(
                db_column='id_ingrediente_siesa',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='preparaciones',
                to='nutricion.tablaalimentos2018icbf',
                verbose_name='Ingrediente (ICBF 2018)',
            ),
        ),
        migrations.AlterModelOptions(
            name='tablapreparacioningredientes',
            options={
                'ordering': ['id_preparacion__preparacion', 'id_ingrediente_siesa__nombre_del_alimento'],
                'verbose_name': 'Ingrediente de Preparación',
                'verbose_name_plural': 'Ingredientes de Preparaciones',
            },
        ),
    ]
