# Generated by Codex on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0015_migrar_preparacion_ingredientes_a_icbf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablapreparacioningredientes',
            name='gramaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gramaje (g)'),
        ),
    ]

