# Generated by Django 5.2.5 on 2026-02-14 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0016_tablapreparacioningredientes_gramaje'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentesModalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_componente', models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.CASCADE, related_name='componentes_modalidades', to='nutricion.componentesalimentos', verbose_name='Componente de Alimento')),
                ('id_modalidad', models.ForeignKey(db_column='id_modalidad', on_delete=django.db.models.deletion.CASCADE, related_name='componentes_modalidades', to='principal.modalidadesdeconsumo', verbose_name='Modalidad de Consumo')),
            ],
            options={
                'verbose_name': 'Componente por Modalidad',
                'verbose_name_plural': 'Componentes por Modalidad',
                'db_table': 'nutricion_componentes_modalidades',
                'ordering': ['id_componente', 'id_modalidad'],
                'unique_together': {('id_componente', 'id_modalidad')},
                'indexes': [models.Index(fields=['id_componente'], name='nutricion_c_id_comp_1094a5_idx'), models.Index(fields=['id_modalidad'], name='nutricion_c_id_moda_c83791_idx')],
            },
        ),
    ]
