# Generated by Django 5.2.5 on 2026-02-16 00:44
# Migración deshabilitada: Base de datos y modelos ya están sincronizados correctamente

from django.db import migrations


def do_nothing(apps, schema_editor):
    """
    No-op migration: La base de datos y los modelos ya están sincronizados.
    Esta migración se mantiene solo para preservar la cadena de dependencias.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0017_componentesmodalidades_and_more'),
        ('principal', '0002_perfilusuario'),
    ]

    operations = [
        # Migración convertida a no-op para evitar conflictos
        # Los modelos y la BD ya están correctamente sincronizados
        migrations.RunPython(do_nothing, do_nothing),
    ]
