# Generated by Django 5.2.5 on 2026-02-16 00:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def column_exists(schema_editor, table_name, column_name):
    """
    Verifica si una columna existe en una tabla.
    """
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM information_schema.columns
            WHERE table_name = %s AND column_name = %s
        """, [table_name, column_name])
        return cursor.fetchone() is not None


def rename_index_if_exists(apps, schema_editor, model_name, old_name, new_name):
    """
    Renombra un índice solo si existe. Útil para bases de datos nuevas donde
    los índices autogenerados pueden no existir aún.
    """
    db_alias = schema_editor.connection.alias
    connection = schema_editor.connection

    # Verificar si el índice existe
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_indexes
            WHERE indexname = %s
        """, [old_name])
        index_exists = cursor.fetchone() is not None

    if index_exists:
        # Renombrar el índice
        with connection.cursor() as cursor:
            cursor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name}')


def add_semana_field_if_not_exists(apps, schema_editor):
    """
    Agrega el campo 'semana' a la tabla nutricion_tabla_menus solo si no existe.
    """
    if not column_exists(schema_editor, 'nutricion_tabla_menus', 'semana'):
        TablaMenus = apps.get_model('nutricion', 'TablaMenus')
        from django.db import models
        import django.core.validators

        field = models.IntegerField(
            blank=True,
            help_text='Semana 1-4, calculada automáticamente para menús 1-20',
            null=True,
            validators=[
                django.core.validators.MinValueValidator(1),
                django.core.validators.MaxValueValidator(4)
            ],
            verbose_name='Semana del Ciclo'
        )
        field.set_attributes_from_name('semana')

        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE nutricion_tabla_menus
                ADD COLUMN semana INTEGER NULL
                CHECK (semana >= 1 AND semana <= 4)
            """)


def remove_semana_field_if_exists(apps, schema_editor):
    """
    Elimina el campo 'semana' si existe (para reversión).
    """
    if column_exists(schema_editor, 'nutricion_tabla_menus', 'semana'):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("ALTER TABLE nutricion_tabla_menus DROP COLUMN semana")


def rename_indexes_forward(apps, schema_editor):
    """Renombra los índices si existen"""
    rename_index_if_exists(
        apps, schema_editor,
        'requerimientosemanal',
        'nutricion_r_modalid_4d33e5_idx',
        'nutricion_r_modalid_e1a6d0_idx'
    )
    rename_index_if_exists(
        apps, schema_editor,
        'requerimientosemanal',
        'nutricion_r_compone_f7553a_idx',
        'nutricion_r_compone_94b87e_idx'
    )


def rename_indexes_backward(apps, schema_editor):
    """Revierte el renombrado de índices"""
    rename_index_if_exists(
        apps, schema_editor,
        'requerimientosemanal',
        'nutricion_r_modalid_e1a6d0_idx',
        'nutricion_r_modalid_4d33e5_idx'
    )
    rename_index_if_exists(
        apps, schema_editor,
        'requerimientosemanal',
        'nutricion_r_compone_94b87e_idx',
        'nutricion_r_compone_f7553a_idx'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0017_componentesmodalidades_and_more'),
        ('principal', '0002_perfilusuario'),
    ]

    operations = [
        # Ejecutar renombrado condicional de índices
        migrations.RunPython(
            rename_indexes_forward,
            rename_indexes_backward,
        ),
        # Agregar campo 'semana' solo si no existe
        migrations.RunPython(
            add_semana_field_if_not_exists,
            remove_semana_field_if_exists,
        ),
        migrations.AlterField(
            model_name='requerimientosemanal',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_semanales', to='nutricion.componentesalimentos', verbose_name='Componente de Alimento'),
        ),
        migrations.AlterField(
            model_name='requerimientosemanal',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_semanales', to='principal.modalidadesdeconsumo', verbose_name='Modalidad de Consumo'),
        ),
    ]
