# Generated by Django 5.2.5 on 2026-02-16 00:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0017_componentesmodalidades_and_more'),
        ('principal', '0002_perfilusuario'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='requerimientosemanal',
            new_name='nutricion_r_modalid_e1a6d0_idx',
            old_name='nutricion_r_modalid_4d33e5_idx',
        ),
        migrations.RenameIndex(
            model_name='requerimientosemanal',
            new_name='nutricion_r_compone_94b87e_idx',
            old_name='nutricion_r_compone_f7553a_idx',
        ),
        migrations.AddField(
            model_name='tablamenus',
            name='semana',
            field=models.IntegerField(blank=True, help_text='Semana 1-4, calculada automáticamente para menús 1-20', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Semana del Ciclo'),
        ),
        migrations.AlterField(
            model_name='requerimientosemanal',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_semanales', to='nutricion.componentesalimentos', verbose_name='Componente de Alimento'),
        ),
        migrations.AlterField(
            model_name='requerimientosemanal',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_semanales', to='principal.modalidadesdeconsumo', verbose_name='Modalidad de Consumo'),
        ),
    ]
