# Generated by Django 5.2.5 on 2026-02-16 02:15
# Modified to be idempotent with proper state management

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def index_exists(schema_editor, index_name):
    """Verifica si un índice existe en la base de datos."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE schemaname = 'public'
                AND indexname = %s
            );
        """, [index_name])
        return cursor.fetchone()[0]


def column_exists(schema_editor, table_name, column_name):
    """Verifica si una columna existe en una tabla."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public'
                AND table_name = %s
                AND column_name = %s
            );
        """, [table_name, column_name])
        return cursor.fetchone()[0]


def apply_changes(apps, schema_editor):
    """
    Aplica cambios de manera idempotente:
    - Renombra índices solo si los antiguos existen
    - Agrega campo semana solo si no existe
    """
    # Renombrar índices si es necesario
    index_renames = [
        ('nutricion_r_modalid_4d33e5_idx', 'nutricion_r_modalid_e1a6d0_idx'),
        ('nutricion_r_compone_f7553a_idx', 'nutricion_r_compone_94b87e_idx'),
    ]

    for old_name, new_name in index_renames:
        if index_exists(schema_editor, old_name):
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name}')
        elif not index_exists(schema_editor, new_name):
            print(f"⚠️  Warning: Neither {old_name} nor {new_name} exists")

    # Agregar campo semana solo si no existe
    if not column_exists(schema_editor, 'nutricion_tabla_menus', 'semana'):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE nutricion_tabla_menus
                ADD COLUMN semana INTEGER NULL
                CHECK (semana >= 1 AND semana <= 4)
            """)


def reverse_changes(apps, schema_editor):
    """Revertir cambios (para rollback)."""
    # Revertir índices
    index_renames = [
        ('nutricion_r_modalid_e1a6d0_idx', 'nutricion_r_modalid_4d33e5_idx'),
        ('nutricion_r_compone_94b87e_idx', 'nutricion_r_compone_f7553a_idx'),
    ]

    for old_name, new_name in index_renames:
        if index_exists(schema_editor, old_name):
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name}')

    # Eliminar campo semana si existe
    if column_exists(schema_editor, 'nutricion_tabla_menus', 'semana'):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("ALTER TABLE nutricion_tabla_menus DROP COLUMN semana")


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0018_rename_nutricion_r_modalid_4d33e5_idx_nutricion_r_modalid_e1a6d0_idx_and_more'),
        ('principal', '0002_perfilusuario'),
    ]

    operations = [
        # Usar SeparateDatabaseAndState para operaciones idempotentes
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Operaciones idempotentes en la BD
                migrations.RunPython(
                    apply_changes,
                    reverse_changes,
                ),
            ],
            state_operations=[
                # Operaciones que actualizan el estado de Django
                migrations.RenameIndex(
                    model_name='requerimientosemanal',
                    new_name='nutricion_r_modalid_e1a6d0_idx',
                    old_name='nutricion_r_modalid_4d33e5_idx',
                ),
                migrations.RenameIndex(
                    model_name='requerimientosemanal',
                    new_name='nutricion_r_compone_94b87e_idx',
                    old_name='nutricion_r_compone_f7553a_idx',
                ),
                migrations.AddField(
                    model_name='tablamenus',
                    name='semana',
                    field=models.IntegerField(
                        blank=True,
                        help_text='Semana 1-4, calculada automáticamente para menús 1-20',
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4)
                        ],
                        verbose_name='Semana del Ciclo'
                    ),
                ),
                migrations.AlterField(
                    model_name='requerimientosemanal',
                    name='componente',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='requerimientos_semanales',
                        to='nutricion.componentesalimentos',
                        verbose_name='Componente de Alimento'
                    ),
                ),
                migrations.AlterField(
                    model_name='requerimientosemanal',
                    name='modalidad',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='requerimientos_semanales',
                        to='principal.modalidadesdeconsumo',
                        verbose_name='Modalidad de Consumo'
                    ),
                ),
            ],
        ),
    ]
