# Generated by Django 5.2.5 on 2026-02-22 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0030_preparacion_ingrediente_componente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoexcluyenteset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grupoexcluyentesetmiembro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requerimientosemanal',
            name='frecuencia',
            field=models.IntegerField(help_text='Número de veces que debe aparecer este grupo de alimentos en la semana', verbose_name='Frecuencia Semanal'),
        ),
        migrations.AlterField(
            model_name='restriccionalimentoespecifico',
            name='alimento',
            field=models.ForeignKey(db_column='codigo_alimento', on_delete=django.db.models.deletion.CASCADE, related_name='restricciones_subgrupo', to='nutricion.tablaalimentos2018icbf', verbose_name='Alimento ICBF'),
        ),
        migrations.AlterField(
            model_name='restriccionalimentoespecifico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restriccionalimentosubgrupo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
