# Generated by Django 5.2.5 on 2026-03-02 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0032_minuta_patron_completar_rangos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablapreparacioningredientes',
            name='id_grupo_alimentos',
            field=models.ForeignKey(blank=True, db_column='id_grupo_alimentos', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes_preparacion', to='nutricion.gruposalimentos', verbose_name='Grupo del Ingrediente en la Preparación'),
        ),
    ]
