# Generated by Django 5.2.5 on 2026-03-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0038_equivalencia_icbf_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaingredientessiesa',
            name='id_ingrediente_siesa',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código del Producto'),
        ),
        migrations.AlterField(
            model_name='tablaingredientessiesa',
            name='nombre_ingrediente',
            field=models.CharField(max_length=255, verbose_name='Nombre del Producto'),
        ),
    ]
