# Generated by Django 5.2.5 on 2026-03-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0039_alter_tablaingredientessiesa_id_ingrediente_siesa_and_more'),
        ('planeacion', '0004_add_item_to_sedes_educativas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equivalenciaicbfcompras',
            unique_together={('id_alimento_icbf', 'id_programa', 'id_ingrediente_compras')},
        ),
        migrations.AddField(
            model_name='equivalenciaicbfcompras',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Marca el producto preferido cuando hay varios matches. El cálculo de orden de compra lo usa por defecto.', verbose_name='Producto principal'),
        ),
    ]
