"""
Django settings for erp_chvs project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-+cc(y)4gjdo(0q9o)4*%hvd@6-c6)!^7!kw5tx2dzv)g(@jwh4'  # Solo para desarrollo
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Configuración de hosts permitidos
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Railway.app domain automático
RAILWAY_STATIC_URL = os.environ.get('RAILWAY_STATIC_URL')
if RAILWAY_STATIC_URL:
    railway_domain = RAILWAY_STATIC_URL.replace('https://', '').replace('http://', '')
    if railway_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(railway_domain)

def _normalize_csrf_origin(origin: str) -> str:
    """
    Normaliza un origen para CSRF_TRUSTED_ORIGINS agregando esquema si falta.

    Django 4+ requiere que todos los valores en CSRF_TRUSTED_ORIGINS tengan esquema (http:// o https://).
    Esta función agrega automáticamente:
    - http:// para localhost, 127.0.0.1, 0.0.0.0
    - https:// para dominios de producción (*.railway.app, etc.)

    Args:
        origin: URL con o sin esquema (ej: "localhost:8000" o "https://example.com")

    Returns:
        URL normalizada con esquema (ej: "http://localhost:8000" o "https://example.com")
    """
    origin = origin.strip()
    if not origin:
        return ''

    # Si ya tiene esquema, devolverlo tal cual
    if origin.startswith(('http://', 'https://')):
        return origin

    # Agregar http:// para hosts locales
    if origin.startswith(('localhost', '127.0.0.1', '0.0.0.0')):
        return f'http://{origin}'

    # Agregar https:// para dominios de producción
    return f'https://{origin}'


# CSRF Trusted Origins (para Railway y dominios externos)
_csrf_env = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:8000,http://127.0.0.1:8000'
)
CSRF_TRUSTED_ORIGINS = [
    normalized for normalized in (_normalize_csrf_origin(item) for item in _csrf_env.split(','))
    if normalized
]

# Agregar Railway URL si existe (normalizado)
if RAILWAY_STATIC_URL:
    normalized_railway_url = _normalize_csrf_origin(RAILWAY_STATIC_URL)
    if normalized_railway_url and normalized_railway_url not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(normalized_railway_url)

# Configuración de seguridad adicional
if not DEBUG:
    # Configuraciones de seguridad para producción
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_extensions',  # Temporalmente comentado para crear migraciones
    'principal', # aplicación principal, cuando se ejecuta el servidor
    'dashboard',
    'nutricion',
    'planeacion',
    'facturacion',
]

# Cloudinary para MEDIA files (imágenes subidas por usuarios)
# Solo se activa en producción para tener almacenamiento persistente
if not DEBUG:
    INSTALLED_APPS.insert(5, 'cloudinary_storage')  # Antes de staticfiles
    INSTALLED_APPS.append('cloudinary')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Servir archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'principal.middleware.RoleAccessMiddleware',  # El nuevo candado de seguridad
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'erp_chvs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'erp_chvs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Railway suele proveer DATABASE_URL; algunos entornos exponen solo variables PG*
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Configuración local/alterna usando variables individuales
    # Soporta nombres DB_* y también PG* (Railway/Postgres estándar).
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME') or os.environ.get('PGDATABASE', 'erp_chvs'),
            'USER': os.environ.get('DB_USER') or os.environ.get('PGUSER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD') or os.environ.get('PGPASSWORD', 'chvs2025'),
            'HOST': os.environ.get('DB_HOST') or os.environ.get('PGHOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT') or os.environ.get('PGPORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-col'

TIME_ZONE = 'America/Bogota'

# Localización: Usar formato local para mostrar, pero aceptar ambos formatos en formularios
USE_L10N = True
USE_THOUSAND_SEPARATOR = False  # No usar separador de miles en formularios

# Importante: Esto permite que Django acepte tanto punto como coma en formularios
DECIMAL_SEPARATOR = '.'  # Usar punto como separador decimal estándar en formularios

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # Directorio para archivos estáticos durante el desarrollo
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Directorio donde se recopilan archivos estáticos para producción

# Configuración de almacenamiento para Django 5.2+ (SOLO usar STORAGES, NO STATICFILES_STORAGE)
STORAGES = {
    "default": {
        # Cloudinary para MEDIA en producción (almacenamiento persistente)
        # FileSystemStorage en desarrollo (local)
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage" if not DEBUG else "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # StaticFilesStorage de Django (sin Cloudinary)
        # WhiteNoise middleware sirve archivos estáticos en producción
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# NO definir STATICFILES_STORAGE (incompatible con STORAGES en Django 5.2)
# Cloudinary SOLO maneja MEDIA files, NO static files

# Credenciales de Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de IA
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# A dónde redirigir al usuario después de un login exitoso.
LOGIN_REDIRECT_URL = '/dashboard/'

# A dónde redirigir al usuario después de cerrar sesión.
LOGOUT_REDIRECT_URL = '/'
