# Generated by Django 5.2.5 on 2026-02-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionesEducativas',
            fields=[
                ('codigo_ie', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código IE')),
                ('nombre_institucion', models.CharField(max_length=255, verbose_name='Nombre de la Institución')),
                ('id_municipios', models.ForeignKey(db_column='id_municipios', on_delete=django.db.models.deletion.PROTECT, to='principal.principalmunicipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'verbose_name_plural': 'Instituciones Educativas',
                'db_table': 'instituciones_educativas',
                'ordering': ['nombre_institucion'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=200, verbose_name='Nombre del Programa')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha Inicial')),
                ('fecha_final', models.DateField(verbose_name='Fecha Final')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8, verbose_name='Estado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='programas_imagenes/', verbose_name='Imagen del Programa')),
                ('contrato', models.CharField(default='SIN_CONTRATO', max_length=100, verbose_name='Contrato')),
                ('municipio', models.ForeignKey(db_column='id_municipio', on_delete=django.db.models.deletion.PROTECT, to='principal.principalmunicipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='SedesEducativas',
            fields=[
                ('cod_interprise', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código Interprise')),
                ('cod_dane', models.CharField(max_length=50, verbose_name='Código DANE')),
                ('nombre_sede_educativa', models.CharField(max_length=255, verbose_name='Nombre Sede Educativa')),
                ('nombre_generico_sede', models.CharField(default='Sin especificar', max_length=255, verbose_name='Nombre Genérico Sede')),
                ('zona', models.CharField(max_length=1, verbose_name='Zona')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('preparado', models.CharField(max_length=50, verbose_name='Preparado')),
                ('industrializado', models.CharField(max_length=50, verbose_name='Industrializado')),
                ('codigo_ie', models.ForeignKey(db_column='codigo_ie', on_delete=django.db.models.deletion.PROTECT, to='planeacion.institucioneseducativas', verbose_name='Institución Educativa')),
            ],
            options={
                'verbose_name': 'Sede Educativa',
                'verbose_name_plural': 'Sedes Educativas',
                'db_table': 'sedes_educativas',
                'ordering': ['codigo_ie__nombre_institucion', 'nombre_sede_educativa'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionRaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focalizacion', models.CharField(max_length=10, verbose_name='Focalización')),
                ('ano', models.IntegerField(default=2025, verbose_name='Año')),
                ('nombre_programa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Programa')),
                ('cap_am', models.IntegerField(default=0, verbose_name='CAP AM (Complemento Alimentario Preparado AM)')),
                ('cap_pm', models.IntegerField(default=0, verbose_name='CAP PM (Complemento Alimentario Preparado PM)')),
                ('almuerzo_ju', models.IntegerField(default=0, verbose_name='Almuerzo Jornada Única')),
                ('refuerzo', models.IntegerField(default=0, verbose_name='Refuerzo Complemento AM/PM')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('etc', models.ForeignKey(db_column='id_municipio', on_delete=django.db.models.deletion.PROTECT, to='principal.principalmunicipio', verbose_name='ETC (Municipio)')),
                ('nivel_escolar', models.ForeignKey(db_column='id_nivel_grado', on_delete=django.db.models.deletion.PROTECT, to='principal.nivelgradoescolar', verbose_name='Nivel Escolar')),
                ('sede_educativa', models.ForeignKey(db_column='cod_interprise', on_delete=django.db.models.deletion.PROTECT, to='planeacion.sedeseducativas', verbose_name='Sede Educativa')),
            ],
            options={
                'verbose_name': 'Planificación de Raciones',
                'verbose_name_plural': 'Planificaciones de Raciones',
                'db_table': 'planificacion_raciones',
                'ordering': ['etc__nombre_municipio', 'focalizacion', 'sede_educativa__nombre_sede_educativa'],
                'indexes': [models.Index(fields=['etc', 'focalizacion', 'ano'], name='planificaci_id_muni_4996d1_idx'), models.Index(fields=['sede_educativa'], name='planificaci_cod_int_b5ac1f_idx')],
                'unique_together': {('etc', 'focalizacion', 'sede_educativa', 'nivel_escolar', 'ano')},
            },
        ),
    ]
