# Generated by Django 5.2.5 on 2025-09-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionCodindem',
            fields=[
                ('id_codindem', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_departamento', models.IntegerField()),
                ('departamento', models.CharField(max_length=100)),
                ('id_municipio', models.IntegerField()),
                ('municipio', models.CharField(max_length=100)),
                ('id_tipo', models.IntegerField()),
                ('tipo_comedor', models.CharField(max_length=50)),
                ('dane', models.CharField(max_length=20)),
                ('cod_interface', models.CharField(max_length=20, unique=True)),
                ('id_comedor', models.CharField(max_length=50, unique=True)),
                ('institucion', models.CharField(max_length=255)),
                ('sede', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'informacion_codindem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=200, verbose_name='Nombre del Programa')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha Inicial')),
                ('fecha_final', models.DateField(verbose_name='Fecha Final')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8, verbose_name='Estado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='programas_imagenes/', verbose_name='Imagen del Programa')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
    ]
