# Generated by Django 5.2.5 on 2025-09-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informacioncodindem',
            options={'managed': True},
        ),
    ]
