# Generated by Django 5.2.5 on 2026-02-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0002_programamodalidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedeseducativas',
            name='cod_dane',
            field=models.BigIntegerField(verbose_name='Código DANE'),
        ),
    ]
