# Generated by Django 5.2.5 on 2025-09-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0002_alter_informacioncodindem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacioncodindem',
            name='id_comedor',
        ),
    ]
