# Generated by Django 5.2.5 on 2026-02-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0003_cod_dane_biginteger'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedeseducativas',
            name='item',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ítem'),
        ),
    ]
