# Generated by Django 5.2.5 on 2025-09-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0003_remove_informacioncodindem_id_comedor'),
        ('principal', '0007_modalidadesdeconsumo_tipodocumento_tipogenero'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionesEducativas',
            fields=[
                ('codigo_ie', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código IE')),
                ('nombre_institucion', models.CharField(max_length=255, verbose_name='Nombre de la Institución')),
                ('id_municipios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.principalmunicipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'verbose_name_plural': 'Instituciones Educativas',
                'db_table': 'intituciones_educativas',
                'ordering': ['nombre_institucion'],
            },
        ),
        migrations.CreateModel(
            name='SedesEducativas',
            fields=[
                ('cod_interprise', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código Interprise')),
                ('cod_dane', models.CharField(max_length=50, verbose_name='Código DANE')),
                ('nombre_sede_educativa', models.CharField(max_length=255, verbose_name='Nombre Sede Educativa')),
                ('zona', models.CharField(max_length=1, verbose_name='Zona')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('preparado', models.CharField(max_length=50, verbose_name='Preparado')),
                ('industrializado', models.CharField(max_length=50, verbose_name='Industrializado')),
                ('codigo_ie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planeacion.institucioneseducativas', verbose_name='Institución Educativa')),
            ],
            options={
                'verbose_name': 'Sede Educativa',
                'verbose_name_plural': 'Sedes Educativas',
                'db_table': 'sedes_educativas',
                'ordering': ['codigo_ie__nombre_institucion', 'nombre_sede_educativa'],
            },
        ),
        migrations.DeleteModel(
            name='InformacionCodindem',
        ),
    ]
