# Generated by Django 5.2.5 on 2025-09-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0003_remove_informacioncodindem_id_comedor'),
        ('principal', '0007_modalidadesdeconsumo_tipodocumento_tipogenero'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionesEducativas',
            fields=[
                ('codigo_dane', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código DANE')),
                ('nombre_institucion', models.CharField(max_length=255, verbose_name='Nombre de la Institución')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('sector', models.CharField(choices=[('OFICIAL', 'Oficial'), ('PRIVADO', 'Privado'), ('MIXTO', 'Mixto')], default='OFICIAL', max_length=20, verbose_name='Sector')),
                ('rector', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rector/Director')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.principaldepartamento', verbose_name='Departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.principalmunicipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'verbose_name_plural': 'Instituciones Educativas',
                'db_table': 'instituciones_educativas',
                'ordering': ['nombre_institucion'],
            },
        ),
        migrations.CreateModel(
            name='SedesEducativas',
            fields=[
                ('codigo_sede', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código de Sede')),
                ('nombre_sede', models.CharField(max_length=255, verbose_name='Nombre de la Sede')),
                ('direccion', models.TextField(verbose_name='Dirección de la Sede')),
                ('zona', models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], max_length=10, verbose_name='Zona')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('coordinador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordinador')),
                ('tiene_comedor', models.BooleanField(default=False, verbose_name='Tiene Comedor')),
                ('tipo_atencion', models.CharField(blank=True, choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('REFRIGERIO_AM', 'Refrigerio AM'), ('REFRIGERIO_PM', 'Refrigerio PM'), ('COMPLEMENTO', 'Complemento Alimentario'), ('MULTIPLE', 'Múltiples Atenciones')], max_length=50, null=True, verbose_name='Tipo de Atención Alimentaria')),
                ('capacidad_beneficiarios', models.IntegerField(blank=True, null=True, verbose_name='Capacidad de Beneficiarios')),
                ('jornada_manana', models.BooleanField(default=False, verbose_name='Jornada Mañana')),
                ('jornada_tarde', models.BooleanField(default=False, verbose_name='Jornada Tarde')),
                ('jornada_nocturna', models.BooleanField(default=False, verbose_name='Jornada Nocturna')),
                ('jornada_unica', models.BooleanField(default=False, verbose_name='Jornada Única')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='planeacion.institucioneseducativas', verbose_name='Institución Educativa')),
            ],
            options={
                'verbose_name': 'Sede Educativa',
                'verbose_name_plural': 'Sedes Educativas',
                'db_table': 'sedes_educativas',
                'ordering': ['institucion__nombre_institucion', 'nombre_sede'],
            },
        ),
        migrations.DeleteModel(
            name='InformacionCodindem',
        ),
    ]
