# Generated by Django 5.2.5 on 2025-09-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0004_institucioneseducativas_sedeseducativas_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='institucioneseducativas',
            table='instituciones_educativas',
        ),
    ]
