# Generated by Django 5.2.5 on 2025-09-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0005_alter_institucioneseducativas_table'),
    ]

    operations = [
        # Modificar tabla instituciones_educativas
        migrations.RunSQL(
            # Forward - Modificar tabla instituciones_educativas
            """
            -- Renombrar columna de clave primaria
            ALTER TABLE instituciones_educativas RENAME COLUMN codigo_dane TO codigo_ie;

            -- Renombrar columna de municipio
            ALTER TABLE instituciones_educativas RENAME COLUMN municipio_id TO id_municipios;

            -- Eliminar columnas innecesarias
            ALTER TABLE instituciones_educativas DROP COLUMN IF EXISTS direccion;
            ALTER TABLE instituciones_educativas DROP COLUMN IF EXISTS telefono;
            ALTER TABLE instituciones_educativas DROP COLUMN IF EXISTS email;
            ALTER TABLE instituciones_educativas DROP COLUMN IF EXISTS sector;
            ALTER TABLE instituciones_educativas DROP COLUMN IF EXISTS rector;
            ALTER TABLE instituciones_educativas DROP COLUMN IF EXISTS estado;
            ALTER TABLE instituciones_educativas DROP COLUMN IF EXISTS fecha_creacion;
            ALTER TABLE instituciones_educativas DROP COLUMN IF EXISTS fecha_actualizacion;
            ALTER TABLE instituciones_educativas DROP COLUMN IF EXISTS departamento_id;
            """,
            # Reverse - No se puede revertir completamente
            """
            -- No se puede revertir completamente porque se pierden datos
            SELECT 1;
            """
        ),

        # Modificar tabla sedes_educativas
        migrations.RunSQL(
            # Forward - Modificar tabla sedes_educativas
            """
            -- Renombrar columnas principales
            ALTER TABLE sedes_educativas RENAME COLUMN codigo_sede TO cod_interprise;
            ALTER TABLE sedes_educativas ADD COLUMN cod_dane VARCHAR(50);
            ALTER TABLE sedes_educativas RENAME COLUMN nombre_sede TO nombre_sede_educativa;
            ALTER TABLE sedes_educativas RENAME COLUMN institucion_id TO codigo_ie;

            -- Agregar columnas nuevas requeridas
            ALTER TABLE sedes_educativas ADD COLUMN preparado VARCHAR(50);
            ALTER TABLE sedes_educativas ADD COLUMN industrializado VARCHAR(50);

            -- Eliminar columnas innecesarias
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS telefono;
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS coordinador;
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS tiene_comedor;
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS tipo_atencion;
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS capacidad_beneficiarios;
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS jornada_manana;
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS jornada_tarde;
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS jornada_nocturna;
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS jornada_unica;
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS estado;
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS fecha_creacion;
            ALTER TABLE sedes_educativas DROP COLUMN IF EXISTS fecha_actualizacion;
            """,
            # Reverse
            """
            SELECT 1;
            """
        ),
    ]
