# Generated by Django 5.2.5 on 2025-09-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0006_auto_20250922_1336'),
        ('principal', '0007_modalidadesdeconsumo_tipodocumento_tipogenero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneseducativas',
            name='id_municipios',
            field=models.ForeignKey(db_column='id_municipios', on_delete=django.db.models.deletion.PROTECT, to='principal.principalmunicipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='sedeseducativas',
            name='codigo_ie',
            field=models.ForeignKey(db_column='codigo_ie', on_delete=django.db.models.deletion.PROTECT, to='planeacion.institucioneseducativas', verbose_name='Institución Educativa'),
        ),
    ]
