# Generated by Django 5.2.5 on 2025-09-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0007_alter_institucioneseducativas_id_municipios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='contrato',
            field=models.CharField(default='SIN_CONTRATO', max_length=100, verbose_name='Contrato'),
        ),
    ]
