# Generated by Django 5.2.5 on 2025-09-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0008_programa_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedeseducativas',
            name='nombre_generico_sede',
            field=models.CharField(default='Sin especificar', max_length=255, verbose_name='Nombre Genérico Sede'),
        ),
    ]
