# Generated by Django migration for adding municipio field to Programa model

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_nivelgradoescolar'),
        ('planeacion', '0009_sedeseducativas_nombre_generico_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='municipio',
            field=models.ForeignKey(
                db_column='id_municipio',
                default=1,  # Valor temporal para registros existentes
                on_delete=django.db.models.deletion.PROTECT,
                to='principal.principalmunicipio',
                verbose_name='Municipio'
            ),
            preserve_default=False,
        ),
    ]