# Generated by Django 5.2.5 on 2025-10-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0011_planificacionraciones'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='planificacionraciones',
            new_name='planificaci_id_muni_4996d1_idx',
            old_name='planificaci_etc_id_8e7a3d_idx',
        ),
        migrations.RenameIndex(
            model_name='planificacionraciones',
            new_name='planificaci_cod_int_b5ac1f_idx',
            old_name='planificaci_cod_int_7f1c5e_idx',
        ),
    ]
