# Generated by Django 5.2.5 on 2025-10-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0012_rename_planificaci_etc_id_8e7a3d_idx_planificaci_id_muni_4996d1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionraciones',
            name='nombre_programa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Programa'),
        ),
    ]
