# Generated by Django 5.2.5 on 2026-04-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiesaCentroCosto',
            fields=[
                ('f284_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Centro Costo')),
                ('f284_descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('f284_id_co', models.CharField(blank=True, max_length=50, verbose_name='ID Centro Operación')),
                ('f284_id_un', models.CharField(blank=True, max_length=50, verbose_name='ID Unidad Negocio')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centro de Costo SIESA',
                'verbose_name_plural': 'Centros de Costo SIESA',
                'db_table': 'siesa_ccostos',
            },
        ),
        migrations.CreateModel(
            name='SiesaCentroOperacion',
            fields=[
                ('f285_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID CO')),
                ('f285_descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centro de Operación SIESA',
                'verbose_name_plural': 'Centros de Operación SIESA',
                'db_table': 'siesa_centros_operaciones',
            },
        ),
        migrations.CreateModel(
            name='SiesaConcepto',
            fields=[
                ('f145_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Concepto')),
                ('f145_descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('f145_ind_naturaleza', models.CharField(blank=True, max_length=5, verbose_name='Indicador Naturaleza')),
                ('f145_ind_liquidacion', models.CharField(blank=True, max_length=50, verbose_name='Indicador Liquidación')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concepto SIESA',
                'verbose_name_plural': 'Conceptos SIESA',
                'db_table': 'siesa_conceptos',
            },
        ),
        migrations.CreateModel(
            name='SiesaInstalacion',
            fields=[
                ('f157_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Instalación')),
                ('f157_descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('f157_id_co', models.CharField(blank=True, max_length=50, verbose_name='ID Centro Operación')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instalación SIESA',
                'verbose_name_plural': 'Instalaciones SIESA',
                'db_table': 'siesa_instalaciones',
            },
        ),
        migrations.CreateModel(
            name='SiesaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(verbose_name='Payload SIESA')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item SIESA',
                'verbose_name_plural': 'Items SIESA',
                'db_table': 'siesa_items',
            },
        ),
        migrations.CreateModel(
            name='SiesaProyecto',
            fields=[
                ('f107_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Proyecto')),
                ('f107_descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('f107_id_referencia', models.CharField(blank=True, max_length=100, verbose_name='ID Referencia')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto SIESA',
                'verbose_name_plural': 'Proyectos SIESA',
                'db_table': 'siesa_proyectos',
            },
        ),
        migrations.CreateModel(
            name='SiesaSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(verbose_name='Payload SIESA')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitante SIESA',
                'verbose_name_plural': 'Solicitantes SIESA',
                'db_table': 'siesa_solicitantes',
            },
        ),
        migrations.CreateModel(
            name='SiesaSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100, verbose_name='Endpoint')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('registros_insertados', models.IntegerField(default=0, verbose_name='Insertados')),
                ('registros_actualizados', models.IntegerField(default=0, verbose_name='Actualizados')),
                ('errores', models.IntegerField(default=0, verbose_name='Errores')),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=10)),
                ('detalle_error', models.TextField(blank=True, verbose_name='Detalle error')),
            ],
            options={
                'verbose_name': 'Log de Sincronización SIESA',
                'verbose_name_plural': 'Logs de Sincronización SIESA',
                'db_table': 'siesa_sync_log',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='SiesaTipoDocumento',
            fields=[
                ('f021_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Tipo Documento')),
                ('f021_descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento SIESA',
                'verbose_name_plural': 'Tipos de Documento SIESA',
                'db_table': 'siesa_tipos_documentos',
            },
        ),
        migrations.CreateModel(
            name='SiesaUbicacion',
            fields=[
                ('f155_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Ubicación')),
                ('f155_descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('f150_id', models.CharField(blank=True, max_length=50, verbose_name='ID f150')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ubicación / Bodega SIESA',
                'verbose_name_plural': 'Ubicaciones / Bodegas SIESA',
                'db_table': 'siesa_ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='SiesaUnidadNegocio',
            fields=[
                ('f281_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Unidad Negocio')),
                ('f281_descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad de Negocio SIESA',
                'verbose_name_plural': 'Unidades de Negocio SIESA',
                'db_table': 'siesa_unidades_negocios',
            },
        ),
        migrations.CreateModel(
            name='SiesaMotivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f146_id', models.CharField(max_length=50, verbose_name='ID Motivo')),
                ('f146_id_concepto', models.CharField(max_length=50, verbose_name='ID Concepto')),
                ('f146_ind_naturaleza', models.CharField(blank=True, max_length=5, verbose_name='Indicador Naturaleza')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motivo SIESA',
                'verbose_name_plural': 'Motivos SIESA',
                'db_table': 'siesa_motivos',
                'unique_together': {('f146_id_concepto', 'f146_id')},
            },
        ),
    ]
